### ISSUE TITLE
Updating Index.html file for configuring SAML login

### ISSUE THREAD

**Issue by hemanth136526** [pegasystems/pega-helm-charts#101]
Is there any way we can update index.html file from Helm charts to configure redirecting URL's for SAML login.?

**Comment by dcasavant** [comment]
No, but you can extend the Docker image to provide a custom index.html file if required.

I am going to close this issue since there is an expected method of extension via the Docker image.  If you disagree, please reopen.

**Comment by hemanth136526** [comment]
@dcasavant - But as we use different URL's for different environments i don't think that will be good approach to extend and use different docker images for each environment.

**Comment by hemanth136526** [comment]
> No, but you can extend the Docker image to provide a custom index.html file if required.
> 
> I am going to close this issue since there is an expected method of extension via the Docker image. If you disagree, please reopen.

@dcasavant - But as we use different URL's for different environments i don't think that will be good approach to extend and use different docker images for each environment.
