### ISSUE TITLE
Predefined values depends on DB type

### ISSUE THREAD

**Issue by Max-Levitskiy** [pegasystems/pega-helm-charts#102]
**Is your feature request related to a problem? Please describe.**
We have properties: driverClass, url, driverUri, which are depends on one - dbType and need to be defined for every deployment, but in most case, these properties will always have the same values. 

**Describe the solution you'd like**
- I suggest to set up dbType as postgres by default (most of the deployment use it as recommend DB for Pega).
- Instead of using url, add dbHost and dbName for forming connection string
- For special cases, when we really need custom URI, use the old url parameter.
- Depends on dbType, define driverClass and driverUri and form connection URI with the default for selected database values.
- Everything property can be defined by user. If not set, we use default value.

**Comment by MadhuriArugula** [comment]
> We have properties: driverClass, url, driverUri, which are depends on one - dbType and need to be defined for every deployment, but in most case, these properties will always have the same values.

@Max-Levitskiy Values.yaml is defined inline with setupDatabase.properties file which is used by clients for their regular deployments. 

> * I suggest to set up dbType as postgres by default (most of the deployment use it as recommend DB for Pega).
 
This change can be considered as most of the supported providers use postgres database.
> * Instead of using url, add dbHost and dbName for forming connection string
> * For special cases, when we really need custom URI, use the old url parameter.
> * Depends on dbType, define driverClass and driverUri and form connection URI with the default for selected database values.
> * Everything property can be defined by user. If not set, we use default value.

To maintain consistency with current deployments On-Prem or Cloud, IMO it should be URL than switching to connection string.

**Comment by petejo** [comment]
Expectation on user for providing JDBC driver class and URL is a standard practice.
