### ISSUE TITLE
Do not enable K8s dashboard. Use kubectl commands instead (or cloud provider UI)

### ISSUE THREAD

**Issue by treedy** [pegasystems/pega-helm-charts#122]
**Is your feature request related to a problem? Please describe.**
The Kubernetes dashboard should be disabled according to [CIS GKE Benchmark Recommendation: 6.10.1](https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#disable_kubernetes_dashboard). It appears that the dashboard was enabled to monitor the bring up of deployments and services.
This is found in [Deploying Pega Platform on a GKE cluster](https://github.com/pegasystems/pega-helm-charts/blob/master/docs/Deploying-Pega-on-GKE.md)

**Describe the solution you'd like**
The `kubectl` command can be used with the `--watch` flag to monitor bring up pods and services. 

**Describe alternatives you've considered**
Alternatively instructions on how to use the cloud provider's console would also work.

**Additional context**

**Comment by zitikay** [comment]
k8sdashboard is no longer included  by default. docs section has instructions for deploying if need be
