### ISSUE TITLE
Migrate validation of charts to Helm 3 and deprecate Helm 2 support

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/pega-helm-charts#124]
**Is your feature request related to a problem? Please describe.**
Helm 2 is now in maintenance mode and is no longer being actively developed. Helm 3 is the future.  Most incoming requests have focused around Helm 3. 

Today the terratest test cases still validate using a Helm 2 engine.  Recently terratest [added support for Helm 3](https://github.com/gruntwork-io/terratest/issues/403).

**Describe the solution you'd like**
- Switch validation to Helm 3.
- Update documentation to reflect Helm 2 support EOL going forward.

**Comment by zitikay** [comment]
Given https://github.com/pegasystems/pega-helm-charts/blob/master/terratest/src/test/Gopkg.lock#L146 (github.com/gruntwork-io/terratest/modules/helm v0.28.5) and helm3 support in terratest v0.25.0 this is already taken care of
