### ISSUE TITLE
change to the pega.yaml file for hostname field

### ISSUE THREAD

**Issue by pegamadds** [pegasystems/pega-helm-charts#128]
In this [document change for row 631](https://protect-us.mimecast.com/s/YeKKCv2L48uE6klWuXoRud?domain=github.com), I'm wondering if we should add this info into it.  I spent a couple days trying to track down exactly how to get a valid subdomain here at Pega and our clients may run into something similar.  Just a thought.  -Steve
![image](https://user-images.githubusercontent.com/62910220/78848522-06169580-79e0-11ea-880d-a3ba681760ba.png)

**Comment by zitikay** [comment]
Whether using Route53 or some other DNS service, the hostname you provide *always* has to be properly registered. IMO this doesn't require additional documentation specific to the web-tier, nor "how to register" because it will change depending on which service is used.
