### ISSUE TITLE
Docker image for Pega search for Pega 8.4.1

### ISSUE THREAD

**Issue by hemanth136526** [pegasystems/pega-helm-charts#132]
I see that new version of Pega docker image was released for 8.4.1, but i don't see the docker image available for Pega Search of the same version while i see the last update was made about the same time for the images.

I'm trying to bring up pega environment in our application on 8.4.1. 
Please suggest how can i proceed further.

**Comment by dcasavant** [comment]
It appears to be posted now.  https://hub.docker.com/layers/pegasystems/search/8.4.1/images/sha256-26fd68df2c406f6e34a733dd6749f140dda8a7e404b5b5d70f7d301652e48d02?context=repo

Please reopen if you are still encountering this problem.
