### ISSUE TITLE
Unable to expose Kafka via default chart configuration

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/pega-helm-charts#135]
**Describe the bug**
The default ingress configuration [hard codes the protocol as HTTP](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_pega-gke-ingress.tpl#L39).  This was found in GCP due to the ingress health check failing, but seems to apply to other providers as well.

**To Reproduce**
Deploy using the default configuration and view the stream health check.  Try to access the stream port externally.

**Expected behavior**
All Kubernetes objects are healthy.  Stream is accessible when configured.

**Chart version**
Latest

**Server (if applicable, please complete the following information):**
 - Environment: GCP

**Additional context**
In _addition_ to fixing the ability to deploy the stream tier, it may be easiest to disable its exposure by default in the [values.yaml](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values.yaml#L149) file (and make any required runbook changes).

**Comment by kishorv10** [comment]
Reopening the issue to fix below this [comment](https://github.com/pegasystems/pega-helm-charts/pull/173#pullrequestreview-463391802)
