### ISSUE TITLE
sticky sessions not working in openshift using passthorugh TLS termination

### ISSUE THREAD

**Issue by anant88** [pegasystems/pega-helm-charts#136]
we have set up pega on openshift which uses HAproxy as default LB . Instead of using edge termination we are using passthrough for TLS termination.
We have created our own set of certificates to decrypt the session . Also overwridden tomcat server xml to redirect traffic to 8443 port -refer attached
[Archive.zip](https://github.com/pegasystems/pega-helm-charts/files/4555726/Archive.zip)

Even after setting route to use haproxy.router.openshift.io/balance='source'  (from openshift documents )and using session affinity as ClientIP in service , we are not getting session stickiness .we have also tried adding additional annonation haproxy.router.openshift.io/disable_cookies='true'

is there something we need to add ?

**Comment by dcasavant** [comment]
From the open shift documentation:

> Cookies cannot be set on passthrough routes, because the HTTP traffic cannot be seen. Instead, a number is calculated based on the source IP address, which determines the back-end.
> 
> If back-ends change, the traffic could head to the wrong server, making it less sticky, and if you are using a load-balancer (which hides the source IP) the same number is set for all connections and traffic is sent to the same pod.

[Source](https://docs.openshift.com/container-platform/3.6/architecture/networking/routes.html)

It looks like `edge` and `reencrypt` supports cookie based session affinity on OpenShift.

**Comment by anant88** [comment]
@dcasavant  - does Pega on K8s/openshift  work with client IP session affinity using passthrough ? 
is there a way to use to TLS termination as passthrough and still get sticky sessions / session affinity to work ?

we have tried using client ip persistence and passthrough but we weren't able to get it working .
