### ISSUE TITLE
Traefik load balancing Issue with Multiple Pega Web pods

### ISSUE THREAD

**Issue by hemanth136526** [pegasystems/pega-helm-charts#137]
**Describe the bug**
When we install Traefik and bring up multiple Web pods, when we try to login to he application with SAML, we land into pega login page even if we enter credentials it won't do anything.

While everything is working as expected when we only one web pod.

We're using the below values.yaml file for Traefik

![image](https://user-images.githubusercontent.com/61475618/80972344-9f6c7800-8de3-11ea-81cf-5a3df49f4d48.png)

 **I'm using mostly default configurations in the values file, do we need to add any extra parameters to make traefik working. Can anyone please help me with the steps to make it work or any working copy would be helpful.**

**To Reproduce**

Clone the charts from the Git to your system.
Update Traefik chart.yaml file with the version 1.77.3 and run helm package ./
When you have tz file for traefik, update the values file as in the above screenshot and run
Helm Install in your DEV namespace to bring up Traefik pod.
Paralelly bring up 2 or 3 Pega Web pods by extending default docker image with SAML Configuration and updating index.html file for redirect.
Try to login and you'll see only Pega login page as below and it won't go any further.
![image](https://user-images.githubusercontent.com/61475618/80973021-73052b80-8de4-11ea-95b6-42776a9589ad.png)

**Expected behavior**
When we hit the URL, it should load balance within the pods and route to any of the web pods.

**Chart version**
1. We're using traefik-1.77.3.tgz  file to install traefik(We built this as mentioned in above step)
 ---->  helm install traefik traefik-1.77.3.tgz -f traefik.yaml -n dev
2.We extended pega -web 8.4.1 docker  image and updated index.html file for SAML redirect.

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Environment: [e.g. Amazon EKS, Open Source Kubernetes 1.11, etc.]
 - Database: [e.g. PostgreSQL]

**Additional context**

**Comment by hemanth136526** [comment]
@dcasavant  - After some troubleshooting, we found this issue was related to the annotations missing in Helm chart v1.2.7 which were available in v1.2.4 by default.

We tried to add these annotations to service under web tier but everything we tried didn't get applied.

Can anyone help me adding these parameters to my values.yaml file.

**metadata:
  annotations:
    traefik.ingress.kubernetes.io/affinity: 'true'
    traefik.ingress.kubernetes.io/load-balancer-method: drr
    traefik.ingress.kubernetes.io/max-conn-amount: '10'
    traefik.ingress.kubernetes.io/session-cookie-name: UNIQUE-PEGA-COOKIE-NAME
  name: pega-web
  namespace: mynamepace**

**Comment by dcasavant** [comment]
Hi @hemanth136526, We have updated the default annotations to better reflect a default ALB configuration when deploying on AWS.  You can add these annotations back in yourself by using the annotations parameter on either the [service](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service) or [ingress](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#ingress) objects.  Note that these will _replace_ the OOTB annotations to allow you full configurability in your environment.

**Comment by zitikay** [comment]
Closing based on above comment
