### ISSUE TITLE
Cassandra containers are deployed when action=install

### ISSUE THREAD

**Issue by maracle6** [pegasystems/pega-helm-charts#138]
**Describe the bug**
When using Pega’s helm charts, we can pass an action: install, deploy, or install-deploy.  If I pass in install, the intention is to create an installation job only but not deploy runtime containers.  Currently this works for tomcat and elasticsearch containers, however the Cassandra containers are still deployed if Cassandra is set to true.
 
Charts should check for and skip deployment of Cassandra if action is install or upgrade.

**To Reproduce**
Use
  actions:
    execute: "install"

and

cassandra:
  enabled: true

**Expected behavior**
Only the installation pod should be deployed

**Chart version**
Latest, no customizations

**Comment by cdancy** [comment]
@dcasavant this is the same issue we were seeing internally. Tried disabling cassandra but that didn't seem to work.

@maracle6 did you try passing along the `pega.cassandra.enabled = false` flag to the helm-cli?

**Comment by cdancy** [comment]
@maracle6 confirmed this does work as expected. @dcasavant we may want to add some logic to disable cassandra if "action = install" so that folks don't have to provide it at runtime.

**Comment by APegaDavis** [comment]
@maracle6 is this still an issue?

**Comment by maracle6** [comment]
I don't think so, but I haven't use the install image in quite a while

**Comment by kishorv10** [comment]
This issue is no more observed. I have verified the helm deployment with action `install`. Other than `pega-db-install` no other work loads are getting deployed.  One should make sure to set `cassandra.enabled` to false.
Hence closing the issue.

**Comment by kishorv10** [comment]
Cassandra is a subchart of Pega. Deployment of it is controlled via `cassandra.enabled` flag. Writing conditions based on the deployment action is complex. As it is a simple configuration to overcome the issue, we are proceeding with the closure of it.

Recommendation: Set `cassandra.enabled` to false while performing fresh installation (deployment action `install`)
