### ISSUE TITLE
Batch tier - naming convention

### ISSUE THREAD

**Issue by maracle6** [pegasystems/pega-helm-charts#140]
**Is your feature request related to a problem? Please describe.**
Currently our helm charts supply as a model three tiers: web, batch, and stream.  I’ve noticed in discussions with a few clients that the batch tier can be confusing when a marketing or decisioning application is being used.  Since batch is also a NodeType, overloading this term to apply to the tier causes a bit of confusion (particularly since you might assign NodeType=Batch to a tier that isn't the batch tier)
 
**Describe the solution you'd like**
I thought that background, noninteractive, or utility might be a better default label for this tier.
 
This is just a housekeeping/clarity issue without a functional impact and perhaps it’s just my opinion.

**Comment by zitikay** [comment]
If you look at the values and values-large yaml files, batch tier contains Batch NodeType in both examples. And values-large is an example supporting a decisioning application like you said. These are just examples anyways, feel free to name it anything you like in your values.yaml
