### ISSUE TITLE
unable to build kubernetes objects from release manifest while installing Pega addons

### ISSUE THREAD

**Issue by vijmalik** [pegasystems/pega-helm-charts#142]
I am trying to install Pega addons using helm v3. Using following command. I have listed kubernetes version and helm version at the bottom.
[addonsmasked.zip](https://github.com/pegasystems/pega-helm-charts/files/4601961/addonsmasked.zip)
[addonsmasked.zip](https://github.com/pegasystems/pega-helm-charts/files/4601963/addonsmasked.zip)

 helm install addons pega/addons --namespace pegaaddons --values addons.yaml

Error:
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

**Describe the bug**
Unable install Pega addons using Helm . 

**To Reproduce**
Steps to reproduce the behavior.
1)  Download addons.yaml using following commands: helm inspect values pega/addons > 
   addons.yaml
2) Update addons.yaml to include your AWS EKS cluster info
3) Run follwoing command : helm install addons pega/addons --namespace pegaaddons --values addons.yaml

**Expected behavior**
Should install Pega addons

**Chart version**
What version of the charts are you using?   https://github.com/pegasystems/pega-helm-charts/tree/master/charts
Have you made any customizations? No

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Environment: [e.g. Amazon EKS, Open Source Kubernetes 1.11, etc.]
 - Database: [e.g. PostgreSQL]

**Additional context**

Kuberenets Version:  kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Helm Version: helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Comment by khick77** [comment]
It looks like those versions "apps/v1beta1", "apps/v1beta2" have been deprecated in k8s 1.16
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

try migrating to use the apps/v1 API version

**Comment by vijmalik** [comment]
I know it, but i don't own those repositories as these are open source. Pega uses quite few of them. First its hard to identify the one that is causing issue as there isn't much info from deployment error.

**Comment by khick77** [comment]
I'm entering an internal bug to migrate these versions
