### ISSUE TITLE
client IP session affinity using passthrough

### ISSUE THREAD

**Issue by anant88** [pegasystems/pega-helm-charts#144]
continuation to issue 136

does Pega on K8s/openshift support  with client IP session affinity using passthrough ?
is there a way to use to TLS termination as passthrough and still get sticky sessions / session affinity to work ?

we have tried using client ip persistence and passthrough but we weren't able to get it working .

**Comment by maracle6** [comment]
Pega uses cookie-based session affinity.  You generally can't guarantee that two users won't have the same IP address.  Most layer 7 load balancers support setting an affinity cookie.

**Comment by dcasavant** [comment]
@maracle6 is correct - many networks utilize NAT and as a result multiple clients would appear to be coming from the same IP.  Even with unique IPs, Client IP affinity is not validated and you may encounter issues.  Have you tried a reencrypt option in OpenShift?

**Comment by anant88** [comment]
@maracle6 @dcasavant - we went live to production using re-encrypt couple of weeks ago.
Thank you for answering .
