### ISSUE TITLE
Increase CPU limit for faster container startup

### ISSUE THREAD

**Issue by rrajarap** [pegasystems/pega-helm-charts#145]
**Is your feature request related to a problem? Please describe.**
Currently for Pega nodes cpu limit is set to 2. While it works fine, but for faster server startup we need more cpus.

Faster startup is very important for auto-scaling. 

**Describe the solution you'd like**
For pega nodes modify the default setting for cpu limit to 4.

**Describe alternatives you've considered**
Only way we could speed up engine start up is by doing more things in parallel. Hence it needs more threads to work in parallel, which means it needs more cpus.

**Additional context**

**Comment by dcasavant** [comment]
Tweaking the issue title a bit 👍
