### ISSUE TITLE
ServiceAccount is not configurable

### ISSUE THREAD

**Issue by weitzj** [pegasystems/pega-helm-charts#15]
The Pega Helm chart does not have an option to configure the serviceAccount.

It would be good to have a serviceaccount configurable in order to harden a Pega Installation.

**Comment by cdancy** [comment]
@weitzj what use-cases did you have in mind?

**Comment by weitzjdevk** [comment]
@cdancy Hardening the kubernetes installation by attaching pod-security-policies to a specific serviceaccount. And this service account has the permissions to actually run pega.

**Comment by dcasavant** [comment]
@weitzjdevk Have you implemented this in your own charts?  We could take a look at incorporating it into this repo.

If not, I can add this to our roadmap which would include research around best practices as well.
