### ISSUE TITLE
Compatible version of Linux

### ISSUE THREAD

**Issue by aetuk** [pegasystems/pega-helm-charts#151]
Hi all, I attempted to run the minimal (value-minimal.ymal) helm script on Centos 7.x but was unsuccessful due to a docker XFS issue. Apart from Ubuntu has the team or anyone else  managed to get this working on any other Linux distro? It would useful to include a section detailing o/s and package versions where the scripts have been tested. Thanks.

**Comment by dcasavant** [comment]
Hi @aetuk, this is not a Pega specific issue.

This problem occurs when your docker storage driver is overlay or overlay2 and your filesystem is xfs without d_type enabled (https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites). If you run `docker info` you can check the Storage Driver section to see the relevant info:

![image](https://user-images.githubusercontent.com/8302863/85029782-a90b2e80-b14a-11ea-9f6e-ab6f60b2dabc.png)
 
This problem can manifest in weird ways so I suggest that you check your environments.

**Comment by dcasavant** [comment]
Since this is not related to Pega or the Helm charts, I will close this issue.  Please reopen if you feel the resolution is incorrect.
