### ISSUE TITLE
container "pega-web-tomcat" in pod "pega-web-xxxx" is waiting to start: PodInitializing

### ISSUE THREAD

**Issue by rohit-eaisystems** [pegasystems/pega-helm-charts#153]
my pega.yaml helm installation doesn't go past this.

![image](https://user-images.githubusercontent.com/51824077/84933007-d0cea800-b0f2-11ea-855f-e61c0c0ada7e.png)

when I do kubectl get pods -n mypega I get:
NAME                         READY   STATUS             RESTARTS   AGE
pega-batch-5fc4df6db-mzb8b   0/1     Init:0/1           0          5m32s
pega-search-0                0/1     CrashLoopBackOff   5          5m32s
pega-stream-0                0/1     Init:0/1           0          5m32s
pega-web-6c459cfc74-9r2r8    0/1     Init:0/1           0          5m32s

Also My Azure gateway shows this when I deploy
![image](https://user-images.githubusercontent.com/51824077/84933481-9580a900-b0f3-11ea-860f-0099bdb2af3b.png)

Not sure what is wrong here?

**Comment by rohit-eaisystems** [comment]
I found the issue, 
![image](https://user-images.githubusercontent.com/51824077/85172640-1c1dbd80-b28f-11ea-8051-83a1d9ed6607.png)

Even though I have passed the jdbc url on pega yaml file.

**Comment by dcasavant** [comment]
Can you share your values.yaml file?  Please redact any sensitive information such as passwords.

**Comment by rohit-eaisystems** [comment]
> Can you share your pega yaml file? Please redact any sensitive information such as passwords.

Thanks a lot for your reply. I am pasting my pega.yaml file below.

---
global:
  # This values.yaml file is an example.  For more information about
  # each configuration option, see the project readme.

  # Enter your Kubernetes provider.
  provider: "aks"

  # Deploy Pega nodes
  actions:
    execute: "deploy"

  # Provide JDBC connection information to the Pega relational database
  #   If you are installing or upgrading on IBM DB2, update the udb.conf file in the /charts/pega/charts/installer/config/udb directory with any additional connection properties.
  jdbc:
    #   url	Valid values are:
    #
    #   Oracle              jdbc:oracle:thin:@//localhost:1521/dbName
    #   IBM DB/2 z / OS 	jdbc:db2://localhost:50000/dbName
    #   IBM DB/2            jdbc:db2://localhost:50000/dbName:fullyMaterializeLobData=true;fullyMaterializeInputStreams=true;
    #                       progressiveStreaming=2;useJDBC4ColumnNameAndLabelSemantics=2;
    #   SQL Server          jdbc:sqlserver://localhost:1433;databaseName=dbName;selectMethod=cursor;sendStringParametersAsUnicode=false
    #   PostgreSQL          jdbc:postgresql://localhost:5432/dbName
    url: "jdbc:sqlserver://***:1433; databaseName=***; selectMethod=cursor; sendStringParametersAsUnicode=false"

    #   driverClass 	-- jdbc class.  Valid values are:
    #
    #   Oracle              oracle.jdbc.OracleDriver
    #   IBM DB/2            com.ibm.db2.jcc.DB2Driver
    #   SQL Server          com.microsoft.sqlserver.jdbc.SQLServerDriver
    #   PostgreSQL          org.postgresql.Driver
    driverClass: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    #   pega.database.type	Valid values are: mssql, oracledate, udb, db2zos, postgres
    dbType: "mssql"
    #   For databases that use multiple JDBC driver files (such as DB2), specify comma separated values for 'driverUri'
    driverUri: "https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/8.2.0.jre11/mssql-jdbc-8.2.0.jre11.jar"
    username: "***"
    password: "***"
    # CUSTOM CONNECTION PROPERTIES
    # Add a list of ; delimited connections properties. The list must end with ;
    # For example: connectionProperties=user=usr;password=pwd;
    connectionProperties: ""
    rulesSchema: "pegarules"
    dataSchema: "pegadata"
    customerDataSchema: ""

  # If using a custom Docker registry, supply the credentials here to pull Docker images.
  docker:
    registry:
      url: "***.azurecr.io"
      username: "***"
      password: "***"
      # Docker image information for the Pega docker image, containing the application server.
    pega:
      image: "***.azurecr.io/my-pega:8.4.0"

  # Upgrade specific properties
  upgrade:
    # Configure only for aks/pks
    # Run "kubectl cluster-info" command to get the service host and https service port of kubernetes api server.
    # Example - Kubernetes master is running at https://<service_host>:<https_service_port>
    kube-apiserver:
      serviceHost: "API_SERVICE_ADDRESS"
      httpsServicePort: "SERVICE_PORT_HTTPS"

  # Specify the Pega tiers to deploy
  tier:
    - name: "web"
      # Create a an interactive tier for web users.  This tier uses
      # the WebUser node type and will be exposed via a service to
      # the load balancer.
      nodeType: "WebUser"

      # Pega requestor specific properties
      requestor:
        # Inactivity time after which requestor is passivated
        passivationTimeSec: 900

      service:
        # For help configuring the service block, see the Helm chart documentation
        # https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service
        port: 8099
        targetPort: 8080

      ingress:
        # For help configuring the ingress block including TLS, see the Helm chart documentation
        # https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#ingress

        # Enter the domain name to access web nodes via a load balancer.
        #  e.g. web.mypega.example.com
        domain: "***"
        tls:
          # Enable TLS encryption
          enabled: false
          # secretName:
          # useManagedCertificate: false
          # ssl_annotation:

      replicas: 1
      javaOpts: ""

      pegaDiagnosticUser: ""
      pegaDiagnosticPassword: ""

      deploymentStrategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate

      hpa:
        enabled: true

    - name: "batch"
      # Create a background tier for batch processing.  This tier uses
      # a collection of background node types and will not be exposed to
      # the load balancer.
      nodeType: "BackgroundProcessing,Search,Batch,RealTime,Custom1,Custom2,Custom3,Custom4,Custom5,BIX"

      replicas: 1
      javaOpts: ""

      pegaDiagnosticUser: ""
      pegaDiagnosticPassword: ""

      deploymentStrategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate

      hpa:
        enabled: true

    - name: "stream"
      # Create a stream tier for queue processing.  This tier deploys
      # as a stateful set to ensure durability of queued data. It may
      # be optionally exposed to the load balancer.
      nodeType: "Stream"

      # Pega requestor specific properties
      requestor:
        # Inactivity time after which requestor is passivated
        passivationTimeSec: 900

      service:
        port: 7003
        targetPort: 7003

      ingress:
        # Enter the domain name to access web nodes via a load balancer.
        #  e.g. web.mypega.example.com
        domain: "***"
        tls:
          # Enable TLS encryption
          enabled: false
          # secretName:
          # useManagedCertificate: false
          # ssl_annotation:

      replicas: 2
      cpuRequest: 200m
      memRequest: "6Gi"
      cpuLimit: 2
      memLimit: "8Gi"
      javaOpts: ""
      initialHeap: "4096m"
      maxHeap: "7168m"

      volumeClaimTemplate:
        resources:
          requests:
            storage: 5Gi

# External services

# Cassandra automatic deployment settings.
cassandra:
  enabled: false
  persistence:
    enabled: false
  resources:
    requests:
      memory: "4Gi"
      cpu: 2
    limits:
      memory: "8Gi"
      cpu: 4

# DDS (external Cassandra) connection settings.
# These settings should only be modified if you are using a custom Cassandra deployment.
#dds:
#externalNodes: ""
#port: "9042"
#username: "dnode_ext"
#password: "dnode_ext"

# Elasticsearch deployment settings.
# Note: This Elasticsearch deployment is used for Pega search, and is not the same Elasticsearch deployment used by the EFK stack.
# These search nodes will be deployed regardless of the Elasticsearch configuration above.
pegasearch:
  image: "***/my-pega-search:8.4.0"
  memLimit: "3Gi"
  replicas: 1

# Pega Installer settings.
installer:
  image: "***.azurecr.io/my-pega-installer:8.4.0"
  # Set the initial administrator@pega.com password for your installation.  This will need to be changed at first login.
  # The adminPassword value cannot start with "@".
  adminPassword: "***"
  bypassLoadEngineClasses: "false"
  bypassLoadAssembledClasses: "false"
  # Upgrade specific properties
  upgrade:
    # Type of upgrade
    # Valid values are 'in-place' , 'out-of-place'
    upgradeType: "in-place"
    # Specify target rules schema for migration and upgrade
    targetRulesSchema: ""

**Comment by dcasavant** [comment]
@rohit-eaisystems it does look like your pega.yaml file is properly configured.  Are you able to confirm that the environment variable is making its way into the container?  It should have generated into a configmap first, so you should be able to find it there.  If you need additional debugging assistance, please reach out to [Pega Global Client Support](https://community.pega.com/support).

**Comment by rohit-eaisystems** [comment]
> @rohit-eaisystems it does look like your pega.yaml file is properly configured. Are you able to confirm that the environment variable is making its way into the container? It should have generated into a configmap first, so you should be able to find it there. If you need additional debugging assistance, please reach out to [Pega Global Client Support](https://community.pega.com/support).

@dcasavant 
I checked the pega-environment-config in Config Maps .
I went to portal which was created using "az aks browse --resource-group <resource-group-name> --name <cluster-name>" to check that.

In that there is a valid value in JDBC_URL which I had passed from pega.yaml file in 
jdbc:
    url:
So I am able to find that too, yet for pega-search-0 pod it shows 

  ____                    ____             _             
 |  _ \ ___  __ _  __ _  |  _ \  ___   ___| | _____ _ __ 
 | |_) / _ \/ _` |/ _` | | | | |/ _ \ / __| |/ / _ \ '__|
 |  __/  __/ (_| | (_| | | |_| | (_) | (__|   <  __/ |   
 |_|   \___|\__, |\__,_| |____/ \___/ \___|_|\_\___|_|   
            |___/                              v2.1.0
 
JDBC_URL must be specified.

**Comment by rohit-eaisystems** [comment]
The issue was with the images, so it ran after I used a fresh one.

Right now facing issues with health probe which is causing pods to restart after sometime.

**Comment by rohit-eaisystems** [comment]
> @rohit-eaisystems it does look like your pega.yaml file is properly configured. Are you able to confirm that the environment variable is making its way into the container? It should have generated into a configmap first, so you should be able to find it there. If you need additional debugging assistance, please reach out to [Pega Global Client Support](https://community.pega.com/support).

The issue was with the images, so it ran after I used a fresh one.

Right now facing issues with health probe which is causing pods to restart after sometime.

**Comment by dcasavant** [comment]
@rohit-eaisystems There is a different image for the search Pods.  If you are seeing "Pega Docker" in the log at startup, you are pointed at the wrong one.  Try using the [pegasystems/search](https://hub.docker.com/r/pegasystems/search) docker image for that container instead.

**Comment by rohit-eaisystems** [comment]
> @rohit-eaisystems There is a different image for the search Pods. If you are seeing "Pega Docker" in the log at startup, you are pointed at the wrong one. Try using the [pegasystems/search](https://hub.docker.com/r/pegasystems/search) docker image for that container instead.

Thanks for the help, I used the above images now I am getting stuck when the pods start.
![image](https://user-images.githubusercontent.com/51824077/85275194-9c197280-b49d-11ea-995e-785ba1c9305a.png)

[pega.yaml.txt](https://github.com/pegasystems/pega-helm-charts/files/4812568/pega.yaml.txt)

**Comment by rohit-eaisystems** [comment]
I get below in logs from pega-web-tomcat.

{"app":"","stack":"","@timestamp":"2020-06-22T13:17:27.171Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.web.servlet.WebAppLifeCycleListener","message":"System Start Date: Mon Jun 22 13:17:26 GMT 2020","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:17:28.003Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.web.servlet.WebAppLifeCycleListener","message":"PegaRULES Web Tier 8.4.1","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:17:28.003Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.web.servlet.WebAppLifeCycleListener","message":"PRPC-8.4.1-359: 2020-04-04 09.31 EDT","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:17:28.003Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.web.servlet.WebAppLifeCycleListener","message":"prpc-platform.git (125297a798a5bd1b0045c0abec772ae9268be871)","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:17:28.003Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.web.servlet.WebAppLifeCycleListener","message":"Now starting the PegaRULES Web Tier...","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:17:31.241Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.priv.context.web.WebEnvironment","message":"Web tier using local JNDI context\nfactory = org.apache.naming.java.javaURLContextFactory\n    url = <not specified>\n   path = java:","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:17:31.241Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.pegarules.priv.context.JNDIEnvironment","message":"Web-tier default Engine bean name is EngineBMT","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:18:10.189Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.platform.modules.internal.ModulesBridgeImpl","message":"Initializing engine modules.","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:19:03.554Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.platform.environment.nodeclassification.internal.NodeClassificationImpl","message":"Node is started without applicableNodeTypes. Hence applicableNodeTypes will be the default list: [Search, WebUser, BIX, BackgroundProcessing, Custom1, Custom2, Custom3, Custom4, Custom5, DDS, ADM, Batch, RealTime, RTDG, Stream]","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:19:03.645Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.platform.environment.nodeclassification.internal.NodeClassificationImpl","message":"NodeTypes considered on current node = [Stream, BackgroundProcessing, WebUser, Search] , for given -DNodeType = [ Stream,BackgroundProcessing,WebUser,Search ]","userid":"","pegathread":""}
Located PegaRULES configuration: file:/usr/local/tomcat/webapps/prweb/WEB-INF/classes/prconfig.xml
{"app":"","stack":"","@timestamp":"2020-06-22T13:19:06.368Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.platform.environment.configuration.internal.sources.CommandLineConfigurationSource","message":"Using command line setting: pega-integrationengine\/enablerequestorpools=false","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:19:06.731Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"com.pega.platform.environment.configuration.internal.DefaultConfigurationSource","message":"prconfig.xml merged with prconfig entries in Data-Admin-System-Settings","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:19:09.431Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"DataGrid-Provider","message":"Datagrid module is using undefined datagrid provider","userid":"","pegathread":""}
{"app":"","stack":"","@timestamp":"2020-06-22T13:19:09.618Z","source_host":"pega-minikube-0","level":"INFO","thread_name":"main","@version":1,"tenantid":"","logger_name":"DataGrid-Provider","message":"Datagrid module overridden to use hazelcast datagrid provider","userid":"","pegathread":""}

And I get 

 Normal   Created                 5m31s                  kubelet, aks-agentpool-20230462-1  Created container pega-web-tomcat
  Normal   Started                 5m30s                  kubelet, aks-agentpool-20230462-1  Started container pega-web-tomcat
  Warning  Unhealthy               3s                     kubelet, aks-agentpool-20230462-1  Liveness probe failed: Get http://10.0.0.39:8080/prweb/PRRestService/monitor/pingService/ping: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

When I do kubectl describe pod pega-minikube -n mypega

**Comment by rohit-eaisystems** [comment]
Another log of startup attached.
[logs-from-pega-web-tomcat-in-pega-minikube-0.txt](https://github.com/pegasystems/pega-helm-charts/files/4814398/logs-from-pega-web-tomcat-in-pega-minikube-0.txt)

**Comment by cdancy** [comment]
@rohit-eaisystems how far away is the database? Looks like you've got a fair amount of "database performance" related alert logs showing up.

**Comment by rohit-eaisystems** [comment]
> @rohit-eaisystems how far away is the database? Looks like you've got a fair amount of "database performance" related alert logs showing up.

@cdancy both are in the same region in azure.

**Comment by rohit-eaisystems** [comment]
Able to successfully deploy and install pega on AKS
