### ISSUE TITLE
System Name passing as parameter while deploying by helm charts

### ISSUE THREAD

**Issue by rohit-eaisystems** [pegasystems/pega-helm-charts#154]
**Is your feature request related to a problem? Please describe.**
If I want to add my pega environment on PDC I will need a different system name to differentiate my various systems. By kubernetes method I am not sure how to change this.
In a normal standard environment I will add a new system name and change prconfig.xml and then restart the server.

**Describe the solution you'd like**
Can we create it on the run from helm and change the values in the container.

**Describe alternatives you've considered**
Till now searching a solution for this.

**Additional context**
none

**Comment by rbogendoerfer** [comment]
When using the "install" action of the Pega deployment, you can specify the system name in the installer section:
# Pega Installer settings
installer:
  image: "my-pega-installer-image:8.4.1"
  adminPassword: "my_admin_password"
  systemName: "my_system_name"

To change the system name after the installation the normal out-of-the-box Pega method can be used:
Select Configure > System > Settings > System name and change the system name there. After that restart all application servers or all Pega pods for the change to become active.
Setting the system name in the prconfig.xml file is usually not required and should be avoided in general.

**Comment by rohit-eaisystems** [comment]
@rbogendoerfer  I tried normal out-of-the-box Pega method and also "install" action on a new install, thanks for guiding me on this. I really appreciate your help.
