### ISSUE TITLE
Unable to download Pega logs in text or zip from Pega dev studio

### ISSUE THREAD

**Issue by rohit-eaisystems** [pegasystems/pega-helm-charts#155]
**Describe the bug**
In the pega helm Chart I have added values in 
      pegaDiagnosticUser: ""
      pegaDiagnosticPassword: ""
So when I go to System>Operations>logs then click on log files I get a pop up
![image](https://user-images.githubusercontent.com/51824077/86243193-93bee700-bbc3-11ea-92f1-14cf9d1a9182.png)

I can check logs in it but unable to download the logs in text or zip it asks for username and password.
![image](https://user-images.githubusercontent.com/51824077/86243314-ca94fd00-bbc3-11ea-8cf0-93697532ada7.png)

using the same one passed on      
 pegaDiagnosticUser: ""
 pegaDiagnosticPassword: ""
But unable to get through

**To Reproduce**
The same one described above

**Expected behavior**
By providing the username and password it should let me download the logs

**Chart version**
![image](https://user-images.githubusercontent.com/51824077/86243546-324b4800-bbc4-11ea-951b-f8197e8a84a9.png)

**Server (if applicable, please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/51824077/86243631-59a21500-bbc4-11ea-9471-b5d35c1b6743.png)

 - Environment:  AKS  kubernetes 1.15.11

 - Database: Azure db

**Additional context**
None

**Comment by rohit-eaisystems** [comment]
Also do we have any other methods to download the logs except from pega portal? Can we do logs checking from directly the node? to do sanity check after fresh installation?

**Comment by dcasavant** [comment]
Hi @rohit-eaisystems, Do you have a logging stack suck as EFK deployed?  That will help you aggregate your log files and is the best solution. 

To access the log file download link, you need to set an actual password for the pegaDiagnosticUser.  Leaving it empty effectively disables it.

**Comment by rohit-eaisystems** [comment]
Hi @dcasavant about EFK , in the addons helm I have set
# The following parameters are not used in Azure AKS environments so they are set to false. Enable any of them if your deployment requires the use of one.

traefik:
  enabled: false

aws-alb-ingress-controller:
  enabled: false

metrics-server:
  enabled: false

deploy_efk: &deploy_efk false

elasticsearch:
  enabled: *deploy_efk

kibana:
  enabled: *deploy_efk

fluentd-elasticsearch:
  enabled: *deploy_efk

For password I am passing actual password for the pegaDiagnosticUser but when I use same password when prompted to download.

Also a little background of my setup.

I have 3 Pega deployments running but I deployed addon helm chart only once, and I am using the IP address from Kubernetes load balancer to access the environments. As I noticed after deployment nothing is added on the application gateway automatically so I am not using Application Gateway to access it.
![image](https://user-images.githubusercontent.com/51824077/86359128-3fcd0480-bc8e-11ea-801e-2f2cc615499c.png)

**Comment by rohit-eaisystems** [comment]
For password I am passing actual password for the pegaDiagnosticUser but when I use same password when prompted to download, but yet it doesn't work for me.

**Comment by pega-sagas1** [comment]
@rohit-eaisystems any update on this issue, are you still facing it?
