### ISSUE TITLE
Unable to use pega chart to provision instance using 1.1.1 version of org.unbroken-dome.helm plugin

### ISSUE THREAD

**Issue by sachinsonu** [pegasystems/pega-helm-charts#160]
**Describe the bug**
Using version 1.1.1 of org.unbroken-dome.helm plugin, requirements.yaml is not being considered for Pega chart as the chart API version is considered to be "v2" by default as there is no explicit mention of chart API version in the Chart.yaml.

**To Reproduce**
Apply org.unbroken-dome.helm plugin, version 1.1.1 in a project and try provisioning using Pega chart, you will notice that requirements.yaml will not be considered.

**Expected behavior**
requirements.yaml to be considered for applying dependencies

**Chart version**
1.2.0

**Comment by sachinsonu** [comment]
Raised a pull request for this issue- https://github.com/pegasystems/pega-helm-charts/pull/161

**Comment by dcasavant** [comment]
Merged 👍
