### ISSUE TITLE
AGIC configuration

### ISSUE THREAD

**Issue by amarlingala** [pegasystems/pega-helm-charts#165]
**Describe the bug**
Unable to Install Pega addons yam following the Instructions for AGIC. Below is the error received
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

**To Reproduce**
Follow run book Instructions for AKS deployment. Failing during the below command.
helm install addons pega/addons --namespace pegaaddons --values addons-aks.yaml

**Expected behavior**
Successful Installation.

**Chart version**
Just updated the properties.

**Server (if applicable, please complete the following information):**
 - OS: Windows
 - Environment: AKS
 - Database: MS SQL

**Additional context**

**Comment by rohit-eaisystems** [comment]
hi @amarlingala  I too had the same issue.

https://github.com/pegasystems/pega-helm-charts/issues/162

Pls check this.

**Comment by originalandawesome** [comment]
@rohit-eaisystems @amarlingala, I had the same problem trying to install on EKS. The solution that worked for me was to decrease the kubernetes version to 1.15. Let me know if this works for you.

**Comment by MadhuriArugula** [comment]
The issue is fixed as part of #185
