### ISSUE TITLE
sessionAffinity: None on ingress when using AKS

### ISSUE THREAD

**Issue by rohit-eaisystems** [pegasystems/pega-helm-charts#168]
**Describe the bug**
Session is not getting sticky to one web node when using pega dev studio in multinode setup, it switches frequently between all webnodes and rules does not load and we get blue screen randomly

**To Reproduce**
Login to pega portal and click any rules.

**Expected behavior**
All rules should open without any issue

**Chart version**
1.2.9 with no custom changes

**Server (if applicable, please complete the following information):**

 - Environment: [ AKS ]
 - Database: [ms sql 2017]

**Additional context**
We are currently working on a high priority migration project on which we are migrating on-prem multi-node setup to AKS-multinode setup. This is the only blocker we are facing and the final cherry to the cake ;)
We have followed all the steps of AKS run book, still we are not able to sort this issue.

**Comment by misterdorito** [comment]
This was caused by setting the web and stream ingresses to the same domain -- making them distinct values or removing the stream ingress config (if not leveraging that endpoint) resolves the issue.
