### ISSUE TITLE
Sending logs from stream pod to ELK

### ISSUE THREAD

**Issue by sachinsonu** [pegasystems/pega-helm-charts#169]
**Is your feature request related to a problem? Please describe.**
Debugging an issue using an instance provisioned using HELM charts is at times difficult with just the logs from web pod available in ELK

**Describe the solution you'd like**
Teams often find logs from stream pod such as kafka/controller or kafka/server useful when debugging decisioning capabilities. It would be very useful if these logs are also sent to ELK

**Comment by Emilio-Pega** [comment]
You can pass in the full text of custom log configuration file, does that help for this case?
![Capture](https://user-images.githubusercontent.com/54679517/88654461-6c144f00-d09b-11ea-8623-4ed0b496d45d.PNG)

**Comment by zitikay** [comment]
@sachinsonu are you able to pass in custom config, or do you need stream logging to always be enabled by default?

**Comment by zitikay** [comment]
Please reopen if you require this as an enhancement
