### ISSUE TITLE
Update HPA target average utilization.

### ISSUE THREAD

**Issue by rrajarap** [pegasystems/pega-helm-charts#179]
**Describe the bug**
While increasing the default CPU request size from 200m to 2 cpu as part of issue 145, default hpa targetAverageUtilization is not updated. Currently hpa targetAverageUtilization is set to 700, which means 2*(700%) = 14 cpus. With these settings autoscaling wouldn't not happen from cpu utilization metric point of view.

**Comment by zitikay** [comment]
fixed in PR
