### ISSUE TITLE
Custom annotations support  for AKS ingress

### ISSUE THREAD

**Issue by sanholla** [pegasystems/pega-helm-charts#181]
Clients want to know the configuration of the application gateway time-out settings for AKS:

The documentation does not mention a specific way to configure the time-out for the app gateway:
https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#ingress

The addons uses this configuration automatically, and they need to know how to configure the time-out value that they need on the pega aks.

Application gateway time-out settings, mostly AGIC manages these settings through ingress annotations https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#request-timeout. 
But in current chart, custom annotations support is not available for AKS ingress

**Comment by kishorv10** [comment]
Same support in required for GKE ingress as well

**Comment by rohit-eaisystems** [comment]
> Clients want to know the configuration of the application gateway time-out settings for AKS:
> 
> The documentation does not mention a specific way to configure the time-out for the app gateway:
> https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#ingress
> 
> The addons uses this configuration automatically, and they need to know how to configure the time-out value that they need on the pega aks.
> 
> Application gateway time-out settings, mostly AGIC manages these settings through ingress annotations https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#request-timeout.
> But in current chart, custom annotations support is not available for AKS ingress

We can do

kubectl get ing -n namespace

and select the ingress controller for which timeout needs to be configured.

kubectl edit ing inggressname -n namespace
 
and add the annotations

appgw.ingress.kubernetes.io/request-timeout: "3600"

use the custom value required

![image](https://user-images.githubusercontent.com/51824077/93178405-d10e2c00-f751-11ea-8530-68c66d33147c.png)

I have tried same on my setup and it works!

**Comment by MadhuriArugula** [comment]
#187

**Comment by MadhuriArugula** [comment]
#187
