### ISSUE TITLE
Permission Denied - Pega-DB-install POD

### ISSUE THREAD

**Issue by dhanoa11** [pegasystems/pega-helm-charts#193]
Hi All,

I am getting Permission denied error while trying to run Helm chart using values-minimal.yaml.  My environment is a single cluster node running on Minikube using Docker driver.  The log message from the POD is: 

Checking valid action
Action selected is 'install-deploy'
Downloading database driver: https://jdbc.postgresql.org/download/postgresql-42.2.16.jre6.jar
Loading prlog4j2 from /opt/pega/config/prlog4j2.xml...
cp: cannot create regular file '/opt/pega/kit/scripts/config/prlog4j2.xml': Permission denied

Any clue?  Do I need to provide specific permissions?

**Comment by shashikant-koder** [comment]
Hi @dhanoa11 ,
Looks like you image has some permission issue related to current user. you can check the container file system permissions. You can follow https://github.com/pegasystems/pega-helm-charts/blob/master/docs/building-your-own-Pega-installer-image.md to create your installer image.

Let me know if it works for you.

Regards,
Shashi

**Comment by dhanoa11** [comment]
Hi Shashi,
I am trying to deploy on minikube (tried both docker and virtual box) drivers. 

Looking at the POD events I see it fails to mount volume "pega-volume-installer" - not much information in the event apart from that.
![DB_Install_Fail](https://user-images.githubusercontent.com/72326188/95804570-c6de4e00-0d4e-11eb-96d8-129f87cbd0ce.PNG)


are there any specific volumes that are required by the pod? Has someone deployed Pega helm charts on minikube

**Comment by dhanoa11** [comment]
does the platform/installer image contains:

/opt/pega/kit/scripts
/opt/pega/kit/archives
/opt/pega/kit/rules

**Comment by shashikant-koder** [comment]
Can you please share the pega-installer dockerfile ?

**Comment by dhanoa11** [comment]
I am using platform/installer:8.5.1 image and don't have docker file 
The image layer details https://hub.docker.com/layers/pegasystems/pega/8.5.1/images/sha256-bf8b64bf0fa5b38704d40437ebe919cd50bd4a8d1493633a1f6a8d930a672555?context=explore

My local image history info attached
![Uploading ef17b72a-3759-404f-91d8-5041bb9fe890.PNG…]()

**Comment by dhanoa11** [comment]
Just now triggered the deployment to GKE and same result. This test rules out my doubt related to minikube specific permissions. this indicates something wrong with the platform/installer image itself
![Uploading GJE_Error.PNG…]()

**Comment by dhanoa11** [comment]
Issue has been resolved by building my own installer image and manipulating the permissions on the folder in the image.
