### ISSUE TITLE
Windows Authentication for on-prem SQL server

### ISSUE THREAD

**Issue by shakess1999** [pegasystems/pega-helm-charts#197]
We have deployed Pega in Azure (AKS) and the app requirement is to connect to an external MSSQL Server database that is hosted on-prem. As per the security policy we are asked to use Windows authentication instead of sql authentication that is part of standard jdbc url string.

Please provide the steps/documentation if it's possible to connect this way, thanks.

**Comment by zitikay** [comment]
https://stackoverflow.com/questions/16497998/jdbc-connection-to-mssql-server-in-windows-authentication-mode
You should just be able to pass in `integratedSecurity=true` to the jdbc url
