### ISSUE TITLE
Support for Static  Provisioning Volumes

### ISSUE THREAD

**Issue by dhanoa11** [pegasystems/pega-helm-charts#198]
is there a support for static provisioning of persistence volumes or mapping pvcs for search and stream to different storage classes?
From readme, I understood that I can supply the PVC values such as storage requested and perhaps name too but I don't see any option to configure pass specific storage class.

**Comment by zitikay** [comment]
Short answer, no. There is no way to specify `storageClassName` (See [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1)). If you require this to be added to the [current volume claim template](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_pega-deployment.tpl#L203-L214) please re-open issue with label "Enhancement"
