### ISSUE TITLE
addons dependencies are missing while performing helm dep update

### ISSUE THREAD

**Issue by MadhuriArugula** [pegasystems/pega-helm-charts#219]
**Describe the bug**
While performing helm dep update of addons chart, it gives Error: found in Chart.yaml, but missing in charts/ directory: traefik, metrics-server

**To Reproduce**
Perform helm dep update and check if dependencies are downloaded properly using "helm dep list" under addons 

**Expected behavior**
All chart dependencies should be downloaded properly without any issues.

**Additional context**
The issue is because stable, incubator chart repo used in our charts are deprecated. It should be moved to another repo as per https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by NekhilKotha** [comment]
Fixed via https://github.com/pegasystems/pega-helm-charts/pull/220
