### ISSUE TITLE
Update AWS default loadbalancing alogorithm to LOR from RR

### ISSUE THREAD

**Issue by prasanthKPega** [pegasystems/pega-helm-charts#223]
In AWS update default ALB routing algorithm from RoundRobin to LeastOutstandingRequests  for better performance.

**Comment by saiprasanthkalangi** [comment]
Choosing suitable routing algorithm for the amazon load balancer:
Load testing was done on PegaCluster deployed in Kubernetes (config: 500users and 20 pods)
Tests were performed on both statefull and stateless apps such as AIA, CSApp(DataPage heavy application).
It was observed that LeastOutStandingRequests(LOR) algorithm performed better compared to RoundRobin(RR) in both response times and throughput of the requests served, hence setting it to default.
