### ISSUE TITLE
Getting Issue with the Pega-web cluster container

### ISSUE THREAD

**Issue by cloudteam1** [pegasystems/pega-helm-charts#233]
Hi Team,

We are using the AWS EKS cluster for Pega and while configuring the helm chats our all pods are able to run except the following pods. Could you please help me out why this is showing every time, As I've tried to do this many times, but every time I am getting the same error. 

Waiting - PodInitializing 

After cross checking the logs and here are the main issue.

Error from server (BadRequest): container "pega-web-tomcat" in pod "pega-web-6f87fc7f58-jcfhp" is waiting to start: PodInitializing

Just because of that our rest of the containers are not being worked, 
Error from server (BadRequest): container "pega-web-tomcat" in pod "pega-batch-6c64f87f74-px2t9" is waiting to start: PodInitializing

Our DB pod is succeeded and working but web is not able to launch.

**Comment by MadhuriArugula** [comment]
@cloudteam1 I believe you must be using "install-deploy" as action when you say DB installation is complete and web pods are not coming up. If you are using [values.yaml](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values.yaml), web, batch and stream pods will wait until search pod is in running state. If cassandra is also set to true in same yaml, then Pega pods will come up only after search, cassandra are up and running. 

You can check the init-containers state in Pega pods, this might help you in getting more information.

**Comment by cloudteam1** [comment]
Thanks @MadhuriArugula  It works!

**Comment by MadhuriArugula** [comment]
I'm closing this ISSUE item with the comments provided to your query. Thanks!

**Comment by SuryaRajud09** [comment]
Hi Team,

I am also facing the same issue
" Defaulted container "pega-web-tomcat" out of: pega-web-tomcat, wait-for-pegainstall (init), wait-for-pegasearch (init)
Error from server (BadRequest): container "pega-web-tomcat" in pod "pega-web-55d95d6c57-j5b54" is waiting to start: PodInitializing"

even my pega-search pod is running but still web, batch and stream pods are not running
