### ISSUE TITLE
pega/addons charts in version 1.4.0 are unavailable (returning 404 error)

### ISSUE THREAD

**Issue by rbogendoerfer** [pegasystems/pega-helm-charts#234]
**Describe the bug**
The pega/addons charts version 1.4.0 is not available in the repo. Despite being listed (i.e. when using 'helm search repo pega') trying to access the charts always fails with an error.

**To Reproduce**
The helm repo has been updated (helm repo update). After that accessing the latest pega/addons version 1.4.0 fails.

helm inspect:
$ helm inspect values pega/addons
Error: failed to download "pega/addons" (hint: running `helm repo update` may help)

helm pull:
$ helm pull pega/addons
Error: failed to fetch https://dl.bintray.com/pegasystems/pega-helm-charts/addons-1.4.0.tgz : 404 Not Found

Accessing other versions still works.

**Expected behavior**
The helm commands should work as expected, i.e. display the values or pull the charts from the repo.

**Chart version**
pega/addons version 1.4.0
No modifications, just using the repo https://dl.bintray.com/pegasystems/pega-helm-charts

**Server (if applicable, please complete the following information):**
n/a

**Additional context**
n/a

**Comment by anujgarg06** [comment]
@MadhuriArugula @dcasavant It is still giving error for addon file, seems like 1.4.1 version doesn't exist for it
helm search repo pega
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
pega/pega               1.4.1                           Pega installation on kubernetes
pega/addons             1.4.1           1.0             A Helm chart for Kubernetes
pega/backingservices    1.4.1                           A Helm chart for Kubernetes

>> helm inspect values pega/addons > addons.yaml
Error: failed to download "pega/addons" (hint: running `helm repo update` may help)
>> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "pega" chart repository
Update Complete. ⎈Happy Helming!⎈
>> helm inspect values pega/addons > addons.yaml
Error: failed to download "pega/addons" (hint: running `helm repo update` may help)

**Comment by MadhuriArugula** [comment]
> @MadhuriArugula @dcasavant It is still giving error for addon file, seems like 1.4.1 version doesn't exist for it
> helm search repo pega
> NAME CHART VERSION APP VERSION DESCRIPTION
> pega/pega 1.4.1 Pega installation on kubernetes
> pega/addons 1.4.1 1.0 A Helm chart for Kubernetes
> pega/backingservices 1.4.1 A Helm chart for Kubernetes
> 
> > > helm inspect values pega/addons > addons.yaml
> > > Error: failed to download "pega/addons" (hint: running `helm repo update` may help)
> > > helm repo update
> > > Hang tight while we grab the latest from your chart repositories...
> > > ...Successfully got an update from the "pega" chart repository
> > > Update Complete. ⎈Happy Helming!⎈
> > > helm inspect values pega/addons > addons.yaml
> > > Error: failed to download "pega/addons" (hint: running `helm repo update` may help)

@anujgarg06 the changes are merged to master. As this issue was linked to PR, it got auto-resolved. We will be releasing the version with fix in sometime.
