### ISSUE TITLE
Turning off Reverse DNS lookup 

### ISSUE THREAD

**Issue by raghavf1** [pegasystems/pega-helm-charts#240]
**Describe the bug**
I would like to disable reverse DNS lookups in PRPC platform to reduce amount of configuration required for supporting reverse DNS and also to minimize the impact it has on performance of requests served.

WebStandardImpl.makeEtierRequest(IWebStandard, HttpServletRequest, HttpServletResponse, Map, Object, DirectStreamWriter) has an intelligent way to fetch remote host only the first time when the session is established. It stores the host name in the http session when the session is established for the first time then it uses the value from session rather than resolving from request.

The issue is the value retrieved by makeEtierRequest is not being used at all the places in engine and resolving from request at other places. We can make change to retrieve the host value from session everywhere.

**To Reproduce**
This is non-trivial to reproduce

**Expected behavior**
n/a

**Chart version**
n/a

**Server (if applicable, please complete the following information):**
n/a

**Additional context**
For internal reference, also see US-139237,BUG-256208

**Comment by APegaDavis** [comment]
@raghavf1 going to close this because it's inactive and the PR you opened was recently closed for similar reasons.
