### ISSUE TITLE
Pega 8.5 Installation on TKGI/PKS

### ISSUE THREAD

**Issue by hemanth136526** [pegasystems/pega-helm-charts#243]
**Describe the bug**
Hello,

I'm trying to install Pega Platform 8.5.2 using helm charts on PKS platform. I'm seeing below error when i'm trying to run the install command

Commands I'm using:

helm install lab pega/pega --namespace dev --values lab.yaml --set global.actions.execute=install
-> Error: failed post-install: job failed: BackoffLimitExceeded

Pod Log Errors:

Checking valid action Action selected is 'install' DISTRIBUTION_KIT_URL is not provided, looking for distribution kit in the mount point
Distribution kit source: /opt/pega/mount/kit
The distribution kit is neither mounted at nor downloaded through url ''. Please provide a valid distribution image

**To Reproduce**

Run the pega installation using Pega helm charts on PKS/TKGI on mssql db using following images

Docker images:

pegasystems/pega-installer-ready:latest

pegasystems/pega:8.5.2
pegasystems/search:8.5.2

**Expected behavior**
Pega 8.5.2 should be installed on the DB
**Chart version**
We're using latest version of Helm chart pega/pega
**Server (if applicable, please complete the following information):**
 - Environment: PKS/TKGI
 - Database: MSSQL

Any help on this.?

**Comment by hemanth136526** [comment]
Closing the issue as there was a confusion around the docker images we were using. Resolved the issue now

**Comment by taz-pega-work** [comment]
hi @hemanth136526 - is there anything in the docs that was confusing that we could address and improve the client experience?

**Comment by hemanth136526** [comment]
Hey @taz-pega-work , that was a mistake from my end as I missed to create the 8.5.2 distribution image from the base image.
Documentation was good on this one.

On a Side Note: Is there any way you can provide an example for adding annotations into the yaml file in the documentation, I'm confused how to add below config to yaml file, whatever I tried didn't work

# Service instance for pega-web
kind: Service
apiVersion: v1
metadata:
  # Name of the service for
  name: pega-web
  namespace: {{ env_name }}
  annotations:
   # Enable backend sticky sessions
    traefik.ingress.kubernetes.io/affinity: 'true'
    # Override the default wrr load balancer algorithm.
    traefik.ingress.kubernetes.io/load-balancer-method: drr
    # Sets the maximum number of simultaneous connections to the backend
    # Must be used in conjunction with the label below to take effect
    traefik.ingress.kubernetes.io/max-conn-amount: '10'
    # Manually set the cookie name for sticky sessions
    traefik.ingress.kubernetes.io/session-cookie-name: UNIQUE-PEGA-COOKIE-NAME
spec:
  type: "LoadBalancer"
  # Specification of on which port the service is enabled
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: pega-web
