### ISSUE TITLE
Service End for Bintray

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/pega-helm-charts#244]
JFrog is ending support for Bintray on May 1st. The released assets from this project are currently pushed to Bintray.  This needs to be changed and the documentation updated.  

This issue will be augmented with additional details and decisions around the new artifact publishing solution.  Please follow it for updates.

**Comment by MadhuriArugula** [comment]
@dcasavant @taz-pega-work @ragsns Closing this ISSUE as we have migrated our release cycle to GitHub Pages.
