### ISSUE TITLE
YAML parse error on pega/templates/pega-tier-ingress.yaml

### ISSUE THREAD

**Issue by anujgarg06** [pegasystems/pega-helm-charts#246]
**Describe the bug**
helm install mypega-EKS-demo pega/pega --namespace mypega-eks-demo --values pega.yaml --set global.actions.execute=install-deploy
**Error: YAML parse error on pega/templates/pega-tier-ingress.yaml: error converting YAML to JSON: yaml: line 24: could not find expected ':'**

**To Reproduce**
Follow command above in Description

**Expected behavior**
It shouldn't throw any error.

**Chart version**
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

**Server (if applicable, please complete the following information):**
 - OS: Windows 10
 - Environment: Amazon EKS
 - Database: SQL Server 2019

**Additional context**
**Debug Information:**
elm install mypega-EKS-demo pega/pega --namespace mypega-eks-demo --values pega.yaml --set global.actions.execute=install-deploy --debug --dry-run
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: C:\Users\agarg\AppData\Local\Temp\helm\repository\pega-1.4.1.tgz

Error: YAML parse error on pega/templates/pega-tier-ingress.yaml: error converting YAML to JSON: yaml: line 24: could not find expected ':'
helm.go:81: [debug] error converting YAML to JSON: yaml: line 24: could not find expected ':'
YAML parse error on pega/templates/pega-tier-ingress.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /home/circleci/helm.sh/helm/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:240
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by sraza1983** [comment]
Hello! I have tried it in my local environment and it seems to work once I remove the 'ssl_annotation' field.

          ssl_annotation: "alb.ingress.kubernetes.io/certificate-arn:arn:aws:acm:us-east-1:970684811386:certificate/794dd146-94fe-448a-942c-a10b06e2cdc7"

**Comment by MadhuriArugula** [comment]
@anujgarg06 @sraza1983 the correct way to provide key and value is below -
`alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:970684811386:certificate/794dd146-94fe-448a-942c-a10b06e2cdc7`
Ensure that you provide a space between key `alb.ingress.kubernetes.io/certificate-arn` and value `arn:aws:acm:us-east-1:970684811386:certificate/794dd146-94fe-448a-942c-a10b06e2cdc7` so that helm parses it correctly.

**Comment by misterdorito** [comment]
In context, it should look like:
```
ingress:
  # Enter the domain name to access web nodes via a load balancer.
  # e.g. web.mypega.example.com
  domain: "[ingress domain]"
  tls:
    # Enable TLS encryption
    enabled: true
    # secretName:
    # useManagedCertificate: false
    ssl_annotation: 
	  alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:970684811386:certificate/794dd146-94fe-448a-942c-a10b06e2cdc7
...	  
```
The documentation for this has a bad example that shows the annotation contenton the same line as "ssl_annotation" -- the helm chart consumes the "ssl_annotation" value as a block of yaml and hance the problem.  I will fix the example.

**Comment by misterdorito** [comment]
The misleading doc is docs/Deploying-Pega-on-EKS.md .
