### ISSUE TITLE
JSESSIONID secure only

### ISSUE THREAD

**Issue by shakess1999** [pegasystems/pega-helm-charts#253]
We are running pega 8.4.2 in AKS. How can we set JSESSIONID to secure only?

**Comment by pega-sagas1** [comment]
Please add custom web.xml as per this https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-configuration-files to secure the cookie.

In the custom `web.xml` please add/update below code snippet:

```
<session-config>

    <cookie-config>

        <http-only>true</http-only>

        <secure>true</secure>

    </cookie-config>

</session-config> 
```
