### ISSUE TITLE
MQ connection from container

### ISSUE THREAD

**Issue by emailtowalter** [pegasystems/pega-helm-charts#255]
We uses PEGA container. but need to connect with IBM MQ. It seems that the Tomcat in the container does not have JMS . suspect this may not work. Hence want to ask if anyone has any experience or suggestion? 

We do not want to customize PEGA container to make future migration easier. 

Appreciated.

**Comment by emailtowalter** [comment]
any one?

**Comment by pega-sagas1** [comment]
Please follow these steps to integrate MQ with tomcat on K8s environment:
https://support.pega.com/question/mq-k8s-environment-tomcat

Please let me know if needed any further information.

**Comment by misterdorito** [comment]
Closing this issue as documention has been provided and no additional questions were recieved.
