### ISSUE TITLE
The JDBC DB connection password is stored as clear text

### ISSUE THREAD

**Issue by emailtowalter** [pegasystems/pega-helm-charts#256]
We are using Pega platform docker image 8.5.2 ( https://hub.docker.com/r/pegasystems/pega ) and noticed that the DB password in context.xml is being exposed in cleartext. Is there a way to remove it ( either encrytion, or encoding, or environment variable)  in the pega provided image.It hurts our eye. 

Thanks, 

Walter

**Comment by emailtowalter** [comment]
someone can help?

**Comment by petejo** [comment]
@emailtowalter Please refer to https://cwiki.apache.org/confluence/display/TOMCAT/Password

**Comment by Saurabh-16** [comment]
Issue is addressed via https://github.com/pegasystems/pega-helm-charts/pull/409
