### ISSUE TITLE
Chart should be updated to support Kubernetes 1.16.x

### ISSUE THREAD

**Issue by rajshrimohanks** [pegasystems/pega-helm-charts#27]
Kubernetes v1.16.x has removed a lot of [deprecated API](https://kubernetes.io/docs/setup/release/notes/#deprecations-and-removals)s which this chart still seem to be using. They should be changed to their new versions in order to support Kubernetes v1.16.

**Comment by dcasavant** [comment]
Agreed - added to the backlog.

**Comment by dcasavant** [comment]
Merged.  This will be present in the next release pushed to bintray.
