### ISSUE TITLE
Service configuration issue for AKS

### ISSUE THREAD

**Issue by taz-mon** [pegasystems/pega-helm-charts#28]
After I deployed, the exposed pega-web tier did not get an external IP address. It looks like the TYPE for the tier is NodePort, and for AKS at least, it should be LoadBalancer.
When I manually change pega-web type in the Pega service, the load-balancer provides an IP address immediately.
Should the service be configured so it is LoadBalancer for all environments and all exposed tiers?

**Comment by Emilio-Pega** [comment]
If you go with LoadBalancer as the type, I'd still need the option for NodePort or some override of the "automatic" value

**Comment by dcasavant** [comment]
Fix merged to master.

The service type will now default to `LoadBalancer`.  This is configurable per service in the tiers section.  See [the service documentation](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service-optional) for more information.

Deployment Type | Load Balancer | Service Type
--- | --- | ---
AWS EKS | ALB | `LoadBalancer`
Minikube | None | `NodePort` (default in the minimal values file)
Other K8S environments | Traefik | `LoadBalancer`


This will be part of the v1.2.1 release.

Thanks for the submission and first cut at the fix @taz-mon !
