### ISSUE TITLE
Pega image date settings in openshift is not working properly

### ISSUE THREAD

**Issue by rengithav** [pegasystems/pega-helm-charts#280]
**Describe the bug**

There is a  timezone difference between database server and OpenShift Pods.  We set the env to use TZ=America/Toronto and it is still showing UTC time in the Openshift PODs.

 

**To Reproduce**

connect to openshift terminal of the pega container

$ date

Thu Apr 29 22:39:45 America 2021

$ env | grep TZ

TZ=America/Toronto

$

 

 

**Expected behavior**

The date should display the EDT timezone.

$ date

Thu Apr 29 18:42:18 EDT 2021

$ env | grep TZ

TZ=America/Toronto

$

 

 

**Chart version**

version: "1.2.0"

 

**Server (if applicable, please complete the following information):**

- OS:

 - Environment: Openshift 3.11

- Database: DB2 on AIX
 

**Additional context**

We are pulling the base pega image of 8.5.2 and deploying it in Openshift Container Platform 3.11.

**Comment by MadhuriArugula** [comment]
You can resolve the use case by passing `-Duser.timezone="America/Toronto"` in [values.yaml](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values.yaml#L103)

**Comment by shashikant-koder** [comment]
Ref - https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/RecommendedJVMArgs.md
