### ISSUE TITLE
java.net.UnknownHostException: pega-search-transport: Name or service not known

### ISSUE THREAD

**Issue by charoensri** [pegasystems/pega-helm-charts#294]
**Describe the bug**
Pega Search starts up with 
[2021-05-28T02:10:35,125][WARN ][o.e.d.z.UnicastZenPing   ] [3luSi9Q] failed to resolve host [pega-search-transport]
java.net.UnknownHostException: pega-search-transport: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]

**To Reproduce**
Deploy k8s with values.yaml

**Expected behavior**
Should not have HOST errors

**Chart version**
No customization. 

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Environment: DockerDesktop/WSL2
 - Database:  PostgreSQL

**Additional context** not sure if this is the answer? The error goes away after removing "-tranport" so it is valid host e.g. curl http://pega-search works.

pega\charts\pegasearch\templates\pega-search-deployment.yaml
        env:
        - name: HOST_LIST
          ###Seri
          ###value: {{ template "searchName" . }}-transport
          value: {{ template "searchName" . }}
        - name: ES_JAVA_OPTS
          value: "-Xmx2g -Xms2g"
        - name: UNICAST_HOSTS
          ###Seri
          ###value: {{ template "searchName" . }}-transport
          value: {{ template "searchName" . }}

**Comment by shashikant-koder** [comment]
Can you please share your values.yaml which has been used here ? Please mask sensitive information.

**Comment by charoensri** [comment]
Here it is... 
[values-minimal-credentials-removed.yaml.txt](https://github.com/pegasystems/pega-helm-charts/files/6637451/values-minimal-credentials-removed.yaml.txt)
