### ISSUE TITLE
No basic creds

### ISSUE THREAD

**Issue by rhmoult** [pegasystems/pega-helm-charts#300]
**Describe the bug**
Following the directions at https://github.com/pegasystems/pega-helm-charts/blob/master/charts/addons/README.md in my AWSGovCloud environment results in Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-load-balancer-controller/manifests/v2.1.0: no basic auth credentials

**To Reproduce**
Create EC2-backed K8s cluster, dev-cluster, in us-gov-west-1 region.  
helm repo add pega https://pegasystems.github.io/pega-helm-charts
helm search repo pega
helm inspect values pega/addons > addons.yaml
kubectl create namespace pegaaddonsdev
vim addons.yaml # Set up needed variables
eksctl utils associate-iam-oidc-provider --region=us-gov-west-1 --cluster=dev-cluster --approve
eksctl create iamserviceaccount --cluster="dev-cluster" --namespace=pegaaddonsdev   --name=aws-load-balancer-controller   --attach-policy-arn=arn:aws:iam::#REDACTED#:policy/AWSLoadBalancerControllerIAMPolicy --override-existing-serviceaccounts   --approve
helm install addons pega/addons --namespace pegaaddonsdev --values addons.yaml

**Expected behavior**
kubectl get pods --namespace pegaaddonsdev #OUTPUT
addons-aws-load-balancer-controller-7c5c84bbbc-5s95k   0/1     Running       0          21m
addons-aws-load-balancer-controller-fb95bcd99-2jgct    0/1     Running   0          33m
addons-fluentd-elasticsearch-7f8v4                     1/1     Running            0          127m
addons-fluentd-elasticsearch-g5qk7                     1/1     Running            0          127m
addons-fluentd-elasticsearch-sf47j                     1/1     Running            0          127m
addons-kibana-667796cd55-tbzg9                         1/1     Running            0          127m
addons-metrics-server-66c6768bf4-9mqzq                 1/1     Running            0          127m
elasticsearch-master-0                                 1/1     Running            0          127m
elasticsearch-master-1                                 1/1     Running            0          127m
elasticsearch-master-2                                 1/1     Running            0          127m

**Chart version**
What version of the charts are you using?  Have you made any customizations?
Latest; only filled in required variables

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] RHEL7.9
 - Environment: [e.g. Amazon EKS, Open Source Kubernetes 1.11, etc.] Amazon EKS
 - Database: [e.g. PostgreSQL] PostgreSQL

**Additional context**
#Actual state
kubectl get pods --namespace pegaaddonsdev
NAME                                                   READY   STATUS             RESTARTS   AGE
addons-aws-load-balancer-controller-7c5c84bbbc-5s95k   0/1     ErrImagePull       0          21m
addons-aws-load-balancer-controller-fb95bcd99-2jgct    0/1     ImagePullBackOff   0          33m
addons-fluentd-elasticsearch-7f8v4                     1/1     Running            0          127m
addons-fluentd-elasticsearch-g5qk7                     1/1     Running            0          127m
addons-fluentd-elasticsearch-sf47j                     1/1     Running            0          127m
addons-kibana-667796cd55-tbzg9                         1/1     Running            0          127m
addons-metrics-server-66c6768bf4-9mqzq                 1/1     Running            0          127m
elasticsearch-master-0                                 1/1     Running            0          127m
elasticsearch-master-1                                 1/1     Running            0          127m
elasticsearch-master-2                                 1/1     Running            0          127m

Describe reports the following:
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  24m                  default-scheduler  Successfully assigned pegaaddonsdev/addons-aws-load-balancer-controller-7c5c84bbbc-5s95k to ip-192-168-33-194.us-gov-west-1.compute.internal
  Normal   Pulling    22m (x4 over 24m)    kubelet            Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0"
  Warning  Failed     22m (x4 over 24m)    kubelet            Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-load-balancer-controller/manifests/v2.1.0: no basic auth credentials
  Warning  Failed     22m (x4 over 24m)    kubelet            Error: ErrImagePull
  Normal   BackOff    19m (x21 over 24m)   kubelet            Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0"
  Warning  Failed     4m4s (x88 over 24m)  kubelet            Error: ImagePullBackOff

Going to https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-load-balancer-controller/manifests/v2.1.0 in the browser shows it does, in fact, require creds.  Where should I get them?

**Comment by MadhuriArugula** [comment]
@rhmoult This might be a question to AWS and node configurations as I do not see anything specific to pega-helm-charts.
Have you checked AWS [troubleshooting documents](https://aws.amazon.com/premiumsupport/knowledge-center/eks-ecr-troubleshooting)?

**Comment by rhmoult** [comment]
I was able to resolve this by modifying the helm chart to point to an image in AWSGovCloud, which I found via Google search.
