### ISSUE TITLE
No Init Container in Pod pega-db-install-xxxxx

### ISSUE THREAD

**Issue by tthv7** [pegasystems/pega-helm-charts#331]
I have deployed Pega Platform on my AKS Cluster and got problem with the pod "pega-db-install-xxxxx" which used the pega/installer image. 
As I see in the .yaml file, there is no Init Container created and the restartPolicy is Never. I cant change the restartPolicy. Could anyone help me with this issue? What should I do now? Thank you!

kind: Pod
apiVersion: v1
metadata:
  name: pega-db-install-mp6g9
  generateName: pega-db-install-
  namespace: ourpega
  uid: 0aa69663-5568-4edb-9be3-7c84b003a9b3
  resourceVersion: '713950'
  creationTimestamp: '2021-08-30T18:14:22Z'
  labels:
    controller-uid: f663c8aa-e2b2-4076-a899-8e3a92972b0a
    job-name: pega-db-install
  ownerReferences:
    - apiVersion: batch/v1
      kind: Job
      name: pega-db-install
      uid: f663c8aa-e2b2-4076-a899-8e3a92972b0a
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-08-30T18:14:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:controller-uid': {}
            'f:job-name': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"f663c8aa-e2b2-4076-a899-8e3a92972b0a"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"pega-db-install"}':
              .: {}
              'f:envFrom': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8080,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:resources':
                .: {}
                'f:limits':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/opt/pega/config"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/opt/pega/secrets"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:imagePullSecrets':
            .: {}
            'k:{"name":"pega-registry-secret"}':
              .: {}
              'f:name': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"pega-volume-credentials"}':
              .: {}
              'f:name': {}
              'f:secret':
                .: {}
                'f:defaultMode': {}
                'f:secretName': {}
            'k:{"name":"pega-volume-installer"}':
              .: {}
              'f:configMap':
                .: {}
                'f:defaultMode': {}
                'f:name': {}
              'f:name': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-08-30T18:40:57Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.240.0.69"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
spec:
  volumes:
    - name: pega-volume-credentials
      secret:
        secretName: pega-credentials-secret
        defaultMode: 420
    - name: pega-volume-installer
      configMap:
        name: pega-install-config
        defaultMode: 420
    - name: default-token-q66wg
      secret:
        secretName: default-token-q66wg
        defaultMode: 420
  containers:
    - name: pega-db-install
      image: >-
        registry-innersource.soprasteria.com/pegamvp/pegacloudinstall/installer:8.6.1
      ports:
        - containerPort: 8080
          protocol: TCP
      envFrom:
        - configMapRef:
            name: pega-install-environment-config
      resources:
        limits:
          cpu: '2'
          memory: 6Gi
        requests:
          cpu: '1'
          memory: 5Gi
      volumeMounts:
        - name: pega-volume-installer
          mountPath: /opt/pega/config
        - name: pega-volume-credentials
          mountPath: /opt/pega/secrets
        - name: default-token-q66wg
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: aks-agentpool-10798322-vmss000000
  securityContext: {}
  imagePullSecrets:
    - name: pega-registry-secret
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Succeeded
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-08-30T18:14:22Z'
      reason: PodCompleted
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-08-30T18:40:57Z'
      reason: PodCompleted
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-08-30T18:40:57Z'
      reason: PodCompleted
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-08-30T18:14:22Z'
  hostIP: 10.240.0.4
  podIP: 10.240.0.69
  podIPs:
    - ip: 10.240.0.69
  startTime: '2021-08-30T18:14:22Z'
  containerStatuses:
    - name: pega-db-install
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2021-08-30T18:14:22Z'
          finishedAt: '2021-08-30T18:40:57Z'
          containerID: >-
            containerd://47c2c677f9d31f8da1d2ed3894b9410596033423a7503395ee5dafb062c8a6f9
      lastState: {}
      ready: false
      restartCount: 0
      image: >-
        registry-innersource.soprasteria.com/pegamvp/pegacloudinstall/installer:8.6.1
      imageID: >-
        registry-innersource.soprasteria.com/pegamvp/pegacloudinstall/installer@sha256:fe55a34d0414592814ad3c4fc8ecae7e1d464ae6424541b76f05ffc724c2fa92
      containerID: >-
        containerd://47c2c677f9d31f8da1d2ed3894b9410596033423a7503395ee5dafb062c8a6f9
      started: false
  qosClass: Burstable

**Comment by pega-talba** [comment]
@tthv7 The installer image does not (and should not) have a restart policy. This image is used as part of a Kubernetes Job; the pod that gets created performs the installation process, and exits when complete.

If you already have Pega Platform installed on your database, you do not need to use the installer image, and you should set `actions.execute` to "deploy" in the values.yaml. If you need to perform the database installation, you should instead use "install" or "install-deploy" and then allow the install job to complete.

Unfortunately, the installer does not gracefully handle restarts. This is a limitation of the underlying platform installation, so we can't fix that in the helm charts. If the installation process failed, and this is a fresh installation, you should clean the schemas and re-run the process. It does appear to have run for 26 minutes with a status of Completed and a 0 exit code; can you verify in the pod logs if the installation succeeded?

**Comment by tthv7** [comment]
@pega-talba thank you so much for your answer! 

As I see in the pod log, the status of the pod is succeeded and the container pega-db-install has following state:
  _State: Terminated
      Reason:   Completed
      Exit Code:   0
  Ready:  False_
So the pod is okay, right?

Besides I have 2 pods pending, pega-stream-0 and ourpega-aks-demo-cassandra-2. As I look at the pod logs, it's said the reason ist "Insufficient cpu, Insufficient memory". I have 2 nodes in the cluster with the settings "Gen5, 4 vCores, 32 GB" (I followed the instruction Deploying Pega Platform on an AKS cluster, so I dont understand why it's not enough). 

As I tried to scale the nodes to 3, I got the error 
_Failed to scale node pool 'agentpool' in Kubernetes service 'pega-deploy-cluster'. Error: The specified service CIDR 10.0.0.0/16 is conflicted with an existing subnet CIDR 10.0.0.0/24_

The subnet 10.0.0.0/24 is used for the gateway and because the gateway is in use, I can't change the subnet, so I can't scale the nodes. Maybe you have a suggestion what I could do now? 
Thank you.

**Comment by pega-sagas1** [comment]
for the reason `"Insufficient cpu, Insufficient memory".` Please try to upgrade the cluster size and memory, and for subnet error, Please try to use different range for subnet.
Example:
User different `CIDR Range`:

address_space       = "10.52.0.0/16"
subnet_prefixes     = ["10.52.0.0/24"]

instead of this:

[10.0.0.0/16]
"10.0.0.0/24"
