### ISSUE TITLE
helm install throws error with k8s version 1.22

### ISSUE THREAD

**Issue by kkzz8888** [pegasystems/pega-helm-charts#336]
**Describe the bug**
helm install (with the latest repo as of now) throws the following error on Kubernetes 1.22
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"]

**To Reproduce**
Run helm install... on any Kubernetes cluster of version 1.22.

**Expected behavior**
Helm install should succeed without any errors

**Chart version**
1.6.2 no customization

**Server (if applicable, please complete the following information):**
 - OS: Ubuntu 20.04
 - Environment: Microk8s version v1.22.1
 - Database: PostgreSQL

**Additional context**

**Comment by MadhuriArugula** [comment]
@kkzz8888 We officially do not support Pega Deployments on Kubernetes 1.22 version. This will be taken as an enhancement.

**Comment by zitikay** [comment]
Also note that [charts/pega/charts/installer/templates/pega-installer-role.yaml](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/charts/installer/templates/pega-installer-role.yaml) will need to be updated to work on 1.22. Seeing following warning when using `install-deploy` action:
`W0930 13:55:53.120400   31208 warnings.go:70] rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role`

**Comment by zitikay** [comment]
Available as of release v1.8.2
