### ISSUE TITLE
Unable to configure use of 3rd database driver classes.

### ISSUE THREAD

**Issue by misterdorito** [pegasystems/pega-helm-charts#344]
**Describe the bug**
In https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/config/deploy/context.xml.tmpl#L77 we set the following JNDI binding:
```
<Environment name="prconfig/database/drivers" value="com.microsoft.sqlserver.jdbc.SQLServerDriver;oracle.jdbc.OracleDriver;org.postgresql.Driver;com.ibm.db2.jcc.DB2Driver" type="java.lang.String" />
```

As JNDI bindings take precendence over Data-Admin-System-Settings, it has the impact of not being able to load database driver classes for for JDBC drivers outside of the list specified in the JNDI setting above.

There was probably never a good reason for setting this via JNDI and it should be removed.  

As this setting controls driver classes loaded directly by Pega, it doesn't impact the Pega rulebase as that driver is loaded by the app server as part of a JNDI datasource definition.

**To Reproduce**
If you configure the Data-Admin-System-Setting Pega-Engine.prconfig/database/drivers to load a 3rd party JDBC driver, your changes will not be reflected by system behavior.

**Expected behavior**
If you configure the Data-Admin-System-Setting Pega-Engine.prconfig/database/drivers to load a 3rd party JDBC driver, your changes should be reflected by system behavior.

**Chart version**
This issue has been present in all Pega helm charts versions -- the current version is 1.6.3.

**Server (if applicable, please complete the following information):**
This issue exists indendent of support infrastructure stack as it is a Pega configuration issue.

**Additional context**
If an existing deployment was leveraging the JNDI binding to specify the JDBC driver class of an external database connection used by their Pega deployment, please consult https://community.pega.com/knowledgebase/articles/system-administration/86/defining-database-driver on how to configure this for the Pega Helm Charts for version v1.6.4+.

**Comment by APegaDavis** [comment]
@misterdorito we should probably mention that if users are relying on this setting being present in the context.xml, that they should refer to the Pega Community describing this setting if they wish to leverage Pega Helm Charts versions 1.6.4+: https://community.pega.com/knowledgebase/articles/system-administration/86/defining-database-driver
