### ISSUE TITLE
Pega Platform is still via HTTP after creating secret TLS with SSL certificate

### ISSUE THREAD

**Issue by tthv7** [pegasystems/pega-helm-charts#346]
Hello everyone,
I have deployed Pega Platform on AKS cluster. After successully creating a secret TLS with a free SSL certificate and running the deploy script (incl. changes for using the secret), I saw that the URL of Pega Platform is still HTTP. In the ingresses tab I can see that both pega-web and pega-stream have 2 ports 80 and 443 for HTTP and HTTPS. 
So why is the Pega platform is still through HTTP? What else do I have to do, so that Pega is reached via HTTPS?
Thanks in advance!

**Comment by pega-sagas1** [comment]
@tthv7 is the issue resolved, if not please share the values.yaml for the same.

**Comment by misterdorito** [comment]
@tthv7 we're closing this issue -- if it is still a problem please let us know.
