### ISSUE TITLE
Beta API Usage on GCP

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/pega-helm-charts#347]
**Describe the bug**
GCP deployments utilize a beta API for [networking port configuration](https://github.com/pegasystems/pega-helm-charts/blob/9cabb57ba987fc09784d5f70d164510e6d65cfc8/charts/pega/templates/_pega-service.tpl#L28). It looks like GCP will be deprecating this API in GKE 1.22.

**Chart version**
Latest

**Server (if applicable, please complete the following information):**
 - GKE 1.22+

**Comment by zitikay** [comment]
As of release v1.8.2, pega-helm-charts compatible with k8s v1.22 (including GKE)
