### ISSUE TITLE
Duplicate DB_TYPE entry in environment comfigmap for installer chart

### ISSUE THREAD

**Issue by canaykin** [pegasystems/pega-helm-charts#357]
**Describe the bug**
The key-value pair `DB_TYPE: {{ .Values.global.jdbc.dbType }}` is defined at line 10 and repeated at line 58 in installer chart pega-install-environment-config.yaml:
https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/charts/installer/templates/pega-install-environment-config.yaml

This causes a failure when the chart is used with kustomize (as helm post-renderer) as kustomize fails to validate the kubernetes manifest due to duplicate keys in the configmap.

**Comment by Saurabh-16** [comment]
We need to make the change here to remove DB_TYPE from one place.

**Comment by sudeshjethoe** [comment]
any progress on this? currently facing this issue as well, seems like a small fix...

**Comment by misterdorito** [comment]
Apologies.  This issue was miscategorized internally and didn't get prioritized.
