### ISSUE TITLE
[Questions]Is pega-helm-charts supported with Kubernets Cluster in Alibaba Cloud?

### ISSUE THREAD

**Issue by sharpsound** [pegasystems/pega-helm-charts#36]
Hi Dear,
We are planing to deploy PEGA platform to the k8s cluster hosted in Alibaba Cloud (which is the similar service as EKS, it provides Nginx-ingress-controller by default).
If this helm chart verified in Alibaba Cloud already or not?
If we need to deploy PEGA in Alibaba Cloud, which provider parameter we need to set? "k8s"?
And if Nginx is supported as LB/Ingress-controller?
Thanks so much!
Brs// Kevin

**Comment by dcasavant** [comment]
@sharpsound We have not tested Pega on Alibaba cloud specifically.  If you would like to try a deployment on it, you will need to take a deep dive into the configuration required (including the load balancer, metrics server, volumes, etc.). This will help you identify how to appropriately configure them for your environment.  

I would also suggest reaching out to [Pega Support](https://community.pega.com/support/contact) to provide feedback that you would like to see validation of your cloud.  We do prefer to keep track of what clouds clients are using to help plan our roadmaps and cover validation appropriately.
