### ISSUE TITLE
support for custom certificates to be injectable to infinity 

### ISSUE THREAD

**Issue by smootherbug** [pegasystems/pega-helm-charts#360]
#359 

**Is your feature request related to a problem? Please describe.**
support for custom certificates to be injectable to infinity

**Describe alternatives you've considered**
Added a new configmap, volumemount to mount certificate values to /opt/pega/certs folder directly.

**Additional context**
Currently we have support only for .cer file, X.509 base64 encoded type certificate files

**Comment by misterdorito** [comment]
Is this issue still open?  Is there more work beyond #359 ?

**Comment by petejo** [comment]
Resolved by #359
