### ISSUE TITLE
Missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath

### ISSUE THREAD

**Issue by Virusmater** [pegasystems/pega-helm-charts#372]
When run
`helm install mypega pega/pega --namespace mypega --values pega.yaml`
get
`
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath
`

**To Reproduce**

1. Create Pega installer image in private docker hub
2. Setup postgres with pljava enabled
3. Add pega repo to helm
4. run `$ helm inspect values pega/pega > pega.yaml`
5. Make smallest possible setup using charts/pega/values-minimal.yaml 
6. run `helm install mypega pega/pega --namespace mypega --values pega.yaml`
pega.yaml:
https://pastebin.com/WfDFm7iT

**Expected behavior**
Installation continues

**Chart version**
1.8.2, no customization

**Server:**
 - OS: CentOS Linux release 8.5.2111
 - Environment: 
 ```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

 - Database: PostgreSQL

**Comment by Virusmater** [comment]
Works with older, 1.21.5 release of Kubernetis

**Comment by MadhuriArugula** [comment]
> 
Please use pega-helm-charts release [1.9.0](https://github.com/pegasystems/pega-helm-charts/tree/v1.9.0) where the support was added for Ingress resource supported in 1.22 Kubernetes
