### ISSUE TITLE
global.certificates should be optional

### ISSUE THREAD

**Issue by misterdorito** [pegasystems/pega-helm-charts#374]
**Describe the bug**
Performing a deployment breaks due to failure to mount volume for certificates.  The volume is based on a config map which is conditionally constructed when certificate have been specified.

**To Reproduce**
Perform helm deployment without specifying global.certificates and deployment will fail.

**Expected behavior**
One should be able to perform helm deployments successfully without specifying certificates.

**Chart version**
1.9.0

**Server (if applicable, please complete the following information):**
 - Any

**Additional context**
n/a

**Comment by zitikay** [comment]
^ Available in v1.9.1
