### ISSUE TITLE
addons deployment (1.9.1) fails on Kubernetes version 1.22

### ISSUE THREAD

**Issue by rbogendoerfer** [pegasystems/pega-helm-charts#376]
When trying to deploy traefik through the addons deployment (chart version 1.9.1) the deployment fails on Kubernetes 1.22:
helm -n pegaaddons install pegaaddons pega/addons --values 1.9.1/addons.yaml
Error: INSTALLATION FAILED: failed to install CRD crds/crds.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

Manally fixing the deprecated API version from "v1beta1" to "v1" in the files charts/aws-load-balancer-controller/crds/crds.yaml and charts/ingress-azure/crds/azureingressprohibitedtarget.yaml does not fully fix the problem. Then a new error occurs:
 helm -n pegaaddons install pegaaddons ./addons-1.9.1 --values 1.9.1/addons.yaml
Error: INSTALLATION FAILED: failed to install CRD crds/azureingressprohibitedtarget.yaml: CustomResourceDefinition.apiextensions.k8s.io "azureingressprohibitedtargets.appgw.ingress.k8s.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version, metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111]

So beside the deprecated API versions also the spec for the azure ingress needs fixing.

**Comment by axelgMS** [comment]
Can you try using 1.5.0-rc1 of the AGIC Addon for k8s 1.22.0 to support ingress v1 API ?

_helm install ingress-azure -f helm-config.yaml  application-gateway-kubernetes-ingress/ingress-azure --version 1.5.0-rc1_

**Comment by RyanStan** [comment]
Merged the pr that was mentioned above so this should be fixed now.  Once we merge a pr for issue #22 we'll cut a release and bump the major version of the charts.

**Comment by pega-roska** [comment]
This should now be fixed in 2.0.0
