### ISSUE TITLE
MountVolume.SetUp failed for 3 objects on Minikube

### ISSUE THREAD

**Issue by ljarzyna** [pegasystems/pega-helm-charts#381]
**Describe the bug**
Trying to install Pega using minikube. Unfortunately, there are 3 issues - please see the below screenshot.
I couldn't find any workaround so please help me with this.

![Screenshot 2022-01-28 at 9 14 30 PM](https://user-images.githubusercontent.com/25616979/151600076-e8eca6b1-b0ff-4442-8a94-5c7c4704b2b3.png)

**To Reproduce**
`helm install mypega pega/pega --namespace mypega --values install.yaml`

My install.yaml:

[install.yaml.txt](https://github.com/pegasystems/pega-helm-charts/files/7960940/install.yaml.txt)

**Expected behavior**
Installation is succesful.

**Chart version**
What version of the charts are you using?  Have you made any customizations?

**Server (if applicable, please complete the following information):**
 - OS: MacOS 12.2
 - Environment: Minikube
 - Database: PostgreSQL 12

`kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}`

`helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

`minikube start --cpus 4 --memory 10240 --insecure-registry=192.168.50.44:5005
😄  minikube v1.25.1 on Darwin 12.2 (arm64)
✨  Using the docker driver based on existing profile
❗  You cannot change the memory size for an existing minikube cluster. Please first delete the cluster.
❗  You cannot change the CPUs for an existing minikube cluster. Please first delete the cluster.
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.23.1 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
    ▪ Using image kubernetesui/dashboard:v2.3.1
    ▪ Using image kubernetesui/metrics-scraper:v1.0.7
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default`

**Comment by misterdorito** [comment]
@ljarzyna we are closing this issue -- feel free to reopen it if you're still having issues.
