### ISSUE TITLE
Add HTTP Setting timeout for Azure Application Gateway

### ISSUE THREAD

**Issue by cgijb** [pegasystems/pega-helm-charts#394]
**Is your feature request related to a problem? Please describe.**
Currently we have a script running that updates the HTTP Settings for our Azure Application Gateway that uses the ALI CLI (specifically [this](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-settings?view=azure-cli-latest)). I don't see in the `values.yaml` a place to set this.

**Describe the solution you'd like**
I would like a way to set this in the `values.yaml` (for every major cloud provider would be nice, if possible) for a more cohesive configuratuion management solution.

**Describe alternatives you've considered**
Currently utilizing the [Azure CLI Network AG HTTP Settings](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-settings?view=azure-cli-latest) in Azure DevOps pipelines to correct the issue after the Helm script is deployed to work around it.

**Additional context**
N/A

**Comment by APegaDavis** [comment]
@cgijb could you please elaborate on the usecase and provide an example of what the solution would look like?

**Comment by kishorv10** [comment]
@cgijb As per the Pega AKS [runbook](https://github.com/pegasystems/pega-helm-charts/blob/master/docs/Deploying-Pega-on-AKS.md#creating-an-application-gateway-resource), Azure application gateway creation is not part of the helm chart deployment. It happens before chart deployment. Hence I doubt if providing gateway timeout settings in the value.yaml control the behaviour. However, we would like to know more about the use case. Please revert to us if you are still looking for an enhancement.
