### ISSUE TITLE
pega-db-install: Job has reached the specified backoff limit

### ISSUE THREAD

**Issue by pk-mittal** [pegasystems/pega-helm-charts#400]
Dear team,

I am trying to do a new installation PEGA 8.6.1 on Azure. I have executed pega.yaml file with install action. but the pega-db-install JOB got failed with error as "Job has reached the specified backoff limit"

![image](https://user-images.githubusercontent.com/101399010/158577500-5e497351-5064-4a04-8cce-966f310bb36f.png)

Thanks,
Praveen

**Comment by RyanStan** [comment]
Try pulling the logs from the install pod, these should have more detail.
`kubectl logs pega-db-install-n655m -n <namespace>`

**Comment by pk-mittal** [comment]
Hello Ryan,

It was a DB connection issue. I have resolved it.

Thanks,
Praveen
