### ISSUE TITLE
Azure Managed Identity in Pega Platform - Web Tier

### ISSUE THREAD

**Issue by lenisha** [pegasystems/pega-helm-charts#402]
**Is your feature request related to a problem? Please describe.**
Enable Pega to SQL Server connections using Azure Managed Identity Authentication (Passwordless)

**Describe the solution you'd like**
JDBC driver supports AuthN mode in url https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15

Specifying url in pega values would open connection , but should not pass usename, password to the driver in this mode
``` 
url: "jdbc:sqlserver://<SRV>.database.windows.net:1433;database=<DB>;authentication=ActiveDirectoryMSI;msiClientId=<MI ID>;selectMethod=cursor;responseBuffering=full;sendStringParametersAsUnicode=false;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
```
1. Fails in Pega chart validation as usernane, and password are required in chart validation steps.
Provided Dummy values
```
username: "dummy"
password: "dummy"
```

2. JDBC driver does not accept username, password when authentication=ActiveDirectoryMSI , need to override contextXML setting the DataSource. 

Should be more native support in Pega Charts.

**Describe alternatives you've considered**
Overriding Tomcat Context.xml and removing username,password works, but should be more easy to do inside charts

```
custom:
        contextXML: |-
          <?xml version='1.0' encoding='utf-8'?>
          <Context>
          <WatchedResource>WEB-INF/web.xml</WatchedResource>
          <Manager pathname="" />
          <Resource name="jdbc/PegaRULES"
          auth="Container"
          type="javax.sql.DataSource"
          driverClassName="{{ .Env.JDBC_CLASS }}"
          url="{{ .Env.JDBC_URL }}"
          maxTotal="{{ .Env.JDBC_MAX_ACTIVE }}"
          minIdle="{{ .Env.JDBC_MIN_IDLE }}"
          maxIdle="{{ .Env.JDBC_MAX_IDLE }}"
          maxWaitMillis="{{ .Env.JDBC_MAX_WAIT }}"
          initialSize="{{ .Env.JDBC_INITIAL_SIZE }}"
          connectionProperties="{{ .Env.JDBC_CONNECTION_PROPERTIES }}"
          timeBetweenEvictionRunsMillis="30000"
          minEvictableIdleTimeMillis="60000"
          />
```

**Comment by APegaDavis** [comment]
@lenisha as I mentioned in the other related issue I do not believe this is something the Pega Platform supports at this time.

**Comment by kishorv10** [comment]
The enhancement has been addressed through the above-linked PRs. Kindly go through them and revert in case of any further issues.
