### ISSUE TITLE
Azure Container Registry Images Pull  with Managed Identity

### ISSUE THREAD

**Issue by lenisha** [pegasystems/pega-helm-charts#403]
**Describe the bug**
AKS Clusters could pull images from ACR using Managed Identity and in this case not need to create docker user/password secret for pulling images.

Removed docker.username, docker.password from values but Chart still created and assigned imagePullSecret with dummy values.

Add to Chart ability to skip secret creation when  images pulled using Managed Identity

**Comment by APegaDavis** [comment]
@lenisha does [this enhancement](https://github.com/pegasystems/pega-helm-charts/commit/c865fd4d49fd1435bcf07cd7ff25438a9b313d45) avoid the issues you were seeing?
