### ISSUE TITLE
Exposing connection Timout and training timeout of the GKE Backend configuration

### ISSUE THREAD

**Issue by alemax22** [pegasystems/pega-helm-charts#423]
We have a deployment of Pega in GKE and we are noticing that a lot of the client requests towatds the Pega backend servers were being dropped because of the too stringent connection timeout of the ingress (GKE Loadbalancer).
We have solved that problem by manually increasing the connection timeout and draining timeout in of the GKE backend configuration yaml (by running a kubectl apply -f command).
So It would really appreciated if you are able to Expose these configurations from the https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_pega-gke-backend-config.tpl template file.

**Comment by kishorv10** [comment]
@alemax22 Are you still looking for the enhancement?

**Comment by alemax22** [comment]
Hi [kishorv10](https://github.com/kishorv10), yes I am

**Comment by kishorv10** [comment]
US-512975 (internal)
