### ISSUE TITLE
Missing node selector for the installer pods

### ISSUE THREAD

**Issue by alemax22** [pegasystems/pega-helm-charts#440]
**Describe the bug**
Since our kubernetes cluster contains both linux and windows worker nodes, we would like to have the possibility to add a node selector also for the installer pod. This feature is already present for all the other containers.
This things prevents us from deploying the Pega cluster in our current Kubernetes environment.

**To Reproduce**
Deploy cluster with custom node selector for the installer pods.

**Expected behavior**
Add nodeSelector configuration for the Installer.

**Chart version**
v2.1.1

**Server (if applicable, please complete the following information):**
 - OS: Ubuntu 18.04
 - Environment: Open Source Kubernetes 1.22
 - Database:  PostgreSQL

**Additional context**
None

**Comment by RyanStan** [comment]
We'll add this!

**Comment by kishorv10** [comment]
Support is provided in latest master

**Comment by kishorv10** [comment]
Waiting for new helm chart release

**Comment by MadhuriArugula** [comment]
Fix available from [2.6.1](https://github.com/pegasystems/pega-helm-charts/tree/v2.6.1) release
