### ISSUE TITLE
Pega CTI port is not forwarded to the pods

### ISSUE THREAD

**Issue by alemax22** [pegasystems/pega-helm-charts#456]
**Describe the bug**
We are using the Pega Customer Strategic app with the CTI integration over https, which requires to explicit a dedicated port for receiving the “events” from the telephony system. But the port indicated in the integration is not supported by the load balancer, which does not perform the right port forwarding…

**To Reproduce**
Create a CTI integration in Pega (from Customer service) over https. The events from the telefono system won’t arrive.

**Expected behavior**
Receiving the events from the telephony system

**Chart version**
V2.1

**Server (if applicable, please complete the following information):**
 - Environment: GKE
 - Database: GC PostgreSQL 12

**Additional context**

**Comment by pega-sagas1** [comment]
Can you please provide more information on this?

**Comment by alemax22** [comment]
We are integrating our Customer Service application with AACC (Avaya Aura Contact Center) and the suggested port by Pega to handle all the events from Avaya is 8443. The problem is that the load balancer (of the ingress for the web pods) does not have any forwarding rule to accomodate this requirement.

**Comment by kishorv10** [comment]
Hi @alemax22 You may know that helm charts is enhanced to deploy tomcat TLS certs & access it over https.. Tomcat server port is 8443 & LB port is 443.
So, in this use case as well, invoke or send CTI events to Pega using 443 port via https. Things should work. Can you please try and revert?

**Comment by kishorv10** [comment]
@alemax22 Can you update the latest status?

**Comment by alemax22** [comment]
At the end we used port 443 also for the AACC communication, and until now it is working fine!
