### ISSUE TITLE
Pegasearch runs as privileged

### ISSUE THREAD

**Issue by PegaBasis** [pegasystems/pega-helm-charts#46]
When deploying pega helm chart on Openshift 4.2 we get the following error:

`create Pod pega-search-0 in StatefulSet pega-search failed error: pods "pega-search-0" is forbidden: unable to validate against any security context constraint: [spec.initContainers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed] `

Is it possible to change the image so that pega-search does not run as privileged?

**Comment by cdancy** [comment]
@PegaBasis currently no but there are future plans to remove this requirement (@dcasavant please correct me if I'm wrong).

To get around things there are loads of ways you can do this to configure your environment exactly as you need. For development purposes I always execute the below to get going quick on OpenShift:
```
oc project $DEFAULT_PROJECT
oc adm policy add-scc-to-user anyuid system:serviceaccount:$DEFAULT_PROJECT:default
oc patch scc restricted -p '{"allowPrivilegedContainer": true}
oc patch scc restricted -p '{"runAsUser": {"type":"RunAsAny"}}'
oc patch scc restricted -p '{"allowHostDirVolumePlugin": true}'
```

**Comment by dcasavant** [comment]
The privileged init container is to configure the `vm.max_mem_count` setting.  If you configure it manually for your nodes, you may bypass the privileged init container.  The pegasearch container does not request privileged access.  

For more information, see the readme: https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#search-deployment.  Specifically, the setting `set_vm_max_map_count`.

I will close this question as answered.  Please reopen if you have trouble with this setting.
