### ISSUE TITLE
External Image Pull Secrets

### ISSUE THREAD

**Issue by maracle6** [pegasystems/pega-helm-charts#483]
**Is your feature request related to a problem? Please describe.**
As a Kubernetes administrator, I'd like to reference an external secret for the imagePullSecret so I can avoid putting a plain text password in my values.yaml.  Values files may be checked into source control, used with DevOps tools, or emailed between staff, leading to insecure handling of passwords.  In some cases, credentials for a client-hosted registry may be provisioned into a namespace by cluster administrators without providing credentials directly to project teams.  And this would also be necessary to support use cases where a Kubernetes Operator maintains a rotating secret or integration with a vault product.

**Describe the solution you'd like**
For the pega chart, add a key global.docker.imagepull_secret_names which takes a list of secrets.  Each secret name in the list is added as an element to imagePullSecrets on line 284 of _pega-deployment.tpl. Similar approaches would be needed for any other deployments and statefulsets, and in other charts such as SRS.

Supporting a list would be preferred, in case some images are stored in different registries or repositories that require different credentials.

**Describe alternatives you've considered**
Currently we have only been successful by customizing the templates, which requires ongoing maintenance with each chart release.

**Comment by maracle6** [comment]
Note: the same requirement is needed for any other charts such as backingservices

**Comment by MadhuriArugula** [comment]
This feature is available as part of latest releases. Please review and confirm

**Comment by maracle6** [comment]
This is working for the Pega chart but I don't believe srs or constellation charts have implemented it.  I was told SRS was considering it for Q3.

**Comment by arvasrikanth** [comment]
This issue is being closed as the feature is now available in the latest release. There is a separate [issue](https://github.com/pegasystems/pega-helm-charts/issues/493) regarding SRS or constellation.
