### ISSUE TITLE
file permission error while deploying helm charts on openshift

### ISSUE THREAD

**Issue by pawankumardv2901** [pegasystems/pega-helm-charts#487]
**Describe the bug**
encounbtered following error while deploying charts on openshift

TLS certificate does not exist
ls: cannot access '/opt/pega/artifactory/cert/*': No such file or directory
Using JDBC_URL: jdbc:postgresql://xyzehsjdsjd.us-east-1.rds.amazonaws.com:5438/ddd
folder name: /opt/pega/certs
*
2022/11/29 15:27:44 unable to chmod temp file: chmod /usr/local/tomcat/webapps/ROOT/index.html: operation not permitted
2022/11/29 15:27:44 unable to chmod temp file: chmod /usr/local/tomcat/conf/Catalina/localhost/prweb.xml: operation not permitted
Loading prlog4j2 from /opt/pega/config/prlog4j2.xml...
Loading prconfig from /opt/pega/config/prconfig.xml...
No server.xml was specified in /opt/pega/config/server.xml. Generating from templates.
2022/11/29 15:27:44 unable to chmod temp file: chmod /usr/local/tomcat/conf/server.xml: operation not permitted
No web.xml was specified in /opt/pega/config/web.xml. Using defaults.
No context.xml was specified in /opt/pega/config/context.xml. Generating from templates.
2022/11/29 15:27:44 unable to chmod temp file: chmod /usr/local/tomcat/conf/context.xml: operation not permitted
2022/11/29 15:27:44 unable to chmod temp file: chmod /usr/local/tomcat/conf/tomcat-users.xml: operation not permitted

**To Reproduce**
added jdbc drivers and rebuild a new image (attached the dockerfile)

**Expected behavior**
containers deployed without errors
**Chart version**
latest version  1.2.0
**Server (if applicable, please complete the following information):**
 - OS: redhat CoreOS
 - Environment: Openshift
 - Database: PostgreSQL

**Additional context**
<img width="892" alt="deployment error" src="https://user-images.githubusercontent.com/55563135/204573520-fc33074d-5096-48f7-8b00-0c8f67877869.PNG">

**Comment by arvasrikanth** [comment]
@pawankumardv2901  is this still an issue?

**Comment by kishorv10** [comment]
@pawankumardv2901 Is this still an issue? Can you update the latest status?
