### ISSUE TITLE
Traefik session affinity annotations broken for traefik v2.x

### ISSUE THREAD

**Issue by misterdorito** [pegasystems/pega-helm-charts#489]
Traefik session affinity annotations broken for traefik v2.x.

This happenned when the required version of traefik in the addons chart was up'ed the traefik helm chart version from 1.77.1 (v1.x version of traefik) to 10.9.0 (v2.5.4 of traefik).

Need to replace:
```
traefik.ingress.kubernetes.io/affinity: 'true'
traefik.ingress.kubernetes.io/session-cookie-name: UNIQUE-PEGA-COOKIE-NAME
```
with:
```
traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
traefik.ingress.kubernetes.io/service.sticky.cookie.name: UNIQUE-PEGA-COOKIE-NAME
```

**To Reproduce**
Install traefik from the addons chart, install the pega chart and observe that load balancing doesn't work correctly.

**Chart version**
This was introduced 2/17/2022 in the master -- v2.1.0 of this chart.

**Comment by MadhuriArugula** [comment]
Fix available as part of [2.6.2](https://github.com/pegasystems/pega-helm-charts/tree/v2.6.2) release.
