### ISSUE TITLE
Error when omitting JDBC Driver URI

### ISSUE THREAD

**Issue by maracle6** [pegasystems/pega-helm-charts#50]
We're using an image with the driver baked in.  If we comment out jdbc.driverUri or give it a blank value we get the error:
![DriverURIHelmError](https://user-images.githubusercontent.com/45719028/71131783-aba0c180-21c3-11ea-8edd-73efedd68327.png)

**Comment by dcasavant** [comment]
Resolved with the merge of #52

**Comment by ashishsinghalnl** [comment]
Hi Guys ,I am executing pega.yaml file .but getting below error .

helm install mypega pega/pega --namespace mypega --values pega.yaml
Error: failed to parse pega.yaml: error converting YAML to JSON: yaml: line 35: did not find expected hexdecimal number



I have given uri as : driverUri: "C:\Users\singh610\Downloads/ojdbc7.jar" .please suggest me what to provide here ? what hexadecimal value it is expecting
