### ISSUE TITLE
Capability to resume/debug helm upgrade failures

### ISSUE THREAD

**Issue by SuryaTejaTumati** [pegasystems/pega-helm-charts#505]
Is your feature request related to a problem? Please describe.
For one of the customer, platform upgrade failed while using helm charts and they wanted to resume from that point of failure but seems that capability is not available in the pega helm chart. 

Describe the solution you'd like
We should be able to set automatic.resume=true in SetupDatabase.properties file in our pega helm charts or we should come up with other capability so that debugging and resuming the upgrade are possible.

**Comment by chandra-prakash-reddy** [comment]
Resolved

**Comment by chandra-prakash-reddy** [comment]
https://github.com/pegasystems/pega-helm-charts/blob/master/docs/resuming-rules-upgrade-failures.md
