### ISSUE TITLE
Hazelcast can not be upgraded from 1.0.4 to 1.3.2

### ISSUE THREAD

**Issue by lxm1989** [pegasystems/pega-helm-charts#518]
**Describe the bug**
I am upgrading Pega infinity from 8.7.4 which is using Hazelcast 1.0.4, to 8.8.1 which will use Hazelcat 1.3.2.
DB, webNode, BackgroundProcessing and etc.  are OK. But Hazelcast pods is not in Running status. 

The pods log is below.
{"timestamp":"2023-02-12T14:23:28.102Z",
 "message":"[192.168.67.34]:5701 [PRPC] [5.1.5] Reason of failure for node join: 
 Joining node's version 5.1.5 is not compatible with cluster version 4.1 
 (Rolling Member Upgrades are only supported for the same major version)",
 "logger":"com.pega.hazelcast.v5.security",
 "thread":"hz.priceless_burnell.priority-generic-operation.thread-0",
 "level":"ERROR"}

In the situation of install 8.8.1, not upgrade, hazelcast can works well.

**To Reproduce**
Upgrade Pega infinity from 8.7.4 which is using Hazelcast 1.0.4, to 8.8.1 which will use Hazelcat 1.3.2.

**Expected behavior**
In Upgrade situation, hazelcat still can work well. 

**Chart version**
2.6.2 
No customizations

**Server (if applicable, please complete the following information):**
 - Environment:Amazon EKS
 - Database: PostgreSQL

**Comment by vnihal72** [comment]
1.0.x series is not directly upgradable to 1.3.2. There is a proper Migration steps defined and its available in Pega public facing doc.

https://docs.pega.com/bundle/platform-88/page/platform/deployment/externalization-of-services/update-external-hazelcast.html

**Comment by kishorv10** [comment]
@lxm1989 Are you able to proceed with the upgrade? Can you update us the latest status?

**Comment by lxm1989** [comment]
@kishorv10 I think @kishorv10 have written the reason. So I did not proceed with upgrade.

**Comment by kishorv10** [comment]
@lxm1989 Thank you for the confirmation. I believe you have the necessary documentation.

Do you have any remaining questions regarding the issues? We are planning to close it.

**Comment by kishorv10** [comment]
No further update from the Client hence closing the issue.
