### ISSUE TITLE
Service Session are not sticky when using NodePort

### ISSUE THREAD

**Issue by Emilio-Pega** [pegasystems/pega-helm-charts#53]
The service is not defined to be sticky when using a NodePort (as far as I can tell), this is causing unusual behavior in designer studio when I have replicas >= 2 on the web tie.  Manifests in a ll sorts of unusual ways:

1. sometimes fails to serve static content
2. Can't save-as rules
3. Cannot open some rule
4. Cannot execute some rules
5. Etc...

All these issues go away when I scale back to a single web node.

Based on this https://kubernetes.io/docs/concepts/services-networking/service/ I would like to see `service.spec.sessionAffinity` set to `ClientIP` *at least for the NodePort case*

This is important for producing a helm based SDE with multiple web nodes.

Pega bug: BUG-531671

**Comment by Emilio-Pega** [comment]
After this happening for several days, could no longer reproduce the issue, so closing

**Comment by Emilio-Pega** [comment]
Ok, it reproduced again for Piort, its somewhat inconsistent.  I am re-opening the issue.

On our local K8S I made the fix I proposed above and the issue cleared up

**Comment by Emilio-Pega** [comment]
https://github.com/pegasystems/pega-helm-charts/pull/54

**Comment by kishorv10** [comment]
@Emilio-Pega  Ingress with Traefik is the suggested way to achieve session affinity for Pega web nodes. Are you not using Traefik?

**Comment by Emilio-Pega** [comment]
I have been told by @dcasavant to use `LoadBalancer` with Traefik 

Does this mean plain NodePort *without* a front-end load balancer is not supported by these charts?  

I know that k8s *will* load balance to a NodePort service without a front-end loadbalancer like Traefik.  So my expectation based on the readme's would be that this should/can work without something like Traefik.

If there is a section in the readme that I missed that says this is *not* supported can you please point it out, as I can't find it.

**Comment by Emilio-Pega** [comment]
Its acceptable to me if you say this is not supported, provided that it is documented

**Comment by kishorv10** [comment]
Per documentation, NodePort without a front-end load balancer (for pega-web service) is suggested only for minikube deployments. See [here](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values-minimal.yaml#L69) 
For baremetal K8S deployments, tested and suggested approach is to use Traefik as load balancer, deploy **traefik** service as NodePort, access pega-web via Traefik's node port, see [here](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/addons/README.md#traefik) 
But, there are other ways of achieving it like you have tried. I am not sure if we can call it out explicitly as not supported. @dcasavant What do you think?

**Comment by Emilio-Pega** [comment]
The first instance you refer to (minikube) will still fail with this stickiness issue, especially if you set a higher number of replicas or the replicaset scales up.  There is also nothing i nthis example suggesting that I can't up the replicas. 

Finally, burying the stuff in an *example* doesn't really help me understand if this is just a sample, or an actual restriction

If the intent is not to restrict how NodePort can be used, then I would suggest actually fixing the NodePort stickiness issue....

**Comment by dcasavant** [comment]
@Emilio-Pega I don't believe we provide any _examples_ of NodePort/ClientIP based routing without a load balancer.  As @kishorv10 pointed out, we currently require a load balancer.  I wouldn't mind us revisiting the idea of using NodePort/ClientIP based routing for Minikube, but it is currently not part of the guide.

Given you are using Traefik now, I don't think this is a blocker and I suggest we close this Issue and PR for now.  I would be happy to revisit based on feedback that it may be better to deploy without Traefik for a PE style deployment.

**Comment by Emilio-Pega** [comment]
@dcasavant Makes sense
