### ISSUE TITLE
Ability to configure the circuit breaker's starting mode

### ISSUE THREAD

**Issue by lukaszkarnasiewicz** [pegasystems/pega-helm-charts#541]
**Is your feature request related to a problem? Please describe.**
REST Service's circuit breaker now can also be configured to start in open mode (via a prconfig). Open mode should be set to true in case low latencies for service requests are required immediately after the startup of a new instance (e.g. instances that handle real-time requests in an auto-scaling environment).

**Describe the solution you'd like**
I'd like to be able to set the circuit breaker's mode only for specific tiers ("dh" to be precise)

**Describe alternatives you've considered**
Inject the prconfig using CONTEXT_XML_SNIPPET (via cdhfull.json). This approach however is worse because it cannot be leveraged by Client-Managed Cloud customers.

**Comment by arvasrikanth** [comment]
@lukaszkarnasiewicz Issue is addressed in latest release as part of this [PR](https://github.com/pegasystems/pega-helm-charts/pull/542)
