### ISSUE TITLE
SRS deployment fails, if external ES cluster is not having basic authentication 

### ISSUE THREAD

**Issue by Anand-Kotamsetti** [pegasystems/pega-helm-charts#548]
**Describe the bug**
SRS deployment fails, if external ES cluster is not having basic authentication .

**To Reproduce**
set https://github.com/pegasystems/pega-helm-charts/blob/v2.12.0/charts/backingservices/values.yaml#L39 false 
set https://github.com/pegasystems/pega-helm-charts/blob/v2.12.0/charts/backingservices/values.yaml#L43C4-L45 values
set https://github.com/pegasystems/pega-helm-charts/blob/v2.12.0/charts/backingservices/values.yaml#L57-L58 false

run helm install backingservices pega/backingservices --namespace pegabackingservices --values backingservices.yaml

**Expected behavior**
SRS should spin up successfully even if the ES cluster is not have basic authentication.

**Chart version**
2.12.0

**Server (if applicable, please complete the following information):**
 - Environment: minikube/eks

**Additional context**
Error : secret 'srs-elastic-credentials" not found

**Comment by bhowd1** [comment]
Closed the issue with Fix: #553 in Release: [release/latest ](https://github.com/pegasystems/pega-helm-charts/releases/tag/v2.12.1)
