### ISSUE TITLE
Support TLS configuration in OpenShift Route

### ISSUE THREAD

**Issue by maracle6** [pegasystems/pega-helm-charts#555]
**Is your feature request related to a problem? Please describe.**
Currently, when deploying with OpenShift the pega chart installs a Route.  But there is no way to pass in TLS configuration if the default certificate for the router isn't valid for the domain we've set in the values file.  We must apply the TLS configuration to the route after the helm install, and after any uninstall or upgrade that replaces the Route object.

**Describe the solution you'd like**
Add OpenShift-specific parameters to the ingress block to configure the certificate, key, and caCertificate in the Route's tls block.  The tls block should appear as in this documentation:
https://docs.openshift.com/container-platform/4.12/networking/routes/secured-routes.html#nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate_secured-routes

**Describe alternatives you've considered**
We considered adding a wildcard subdomain to the router's default certificate, but wildcards in certificates isn't allowed by organizational security policy.  We considered adding our specific domains to the router default certificate, however this isn't logistically feasible as the OpenShift cluster is shared and making frequent updates to the default certificate for every project is both risky and cumbersome.  Red Hat's cert-manager operator would be a great solution but has been in technology preview status for some time (may have just gone GA) and requires implementation and integration with a vault product.

**Additional context**
Although putting the TLS key directly in the values file is not an ideal practice, OpenShift doesn't allow use of a secret or file to store the TLS configuration -- it must be configured directly into the Route object.

For documentation purposes, it's useful to note that the certificate should contain only the leaf certificate.  If there are multiple certificates in the signing chain they can be appended and all placed in the caCertificate.

**Comment by arvasrikanth** [comment]
As Issue is fixed in latest release closing the issue
