### ISSUE TITLE
Image failed to pull from the Repo "Hazelcast by using “clusteringServiceImage"

### ISSUE THREAD

**Issue by wreddybeem** [pegasystems/pega-helm-charts#559]
Hello Team, 
When we are trying to deploy the Hazelcast by using “clusteringServiceImage”, It is failing with the below errors.
We tried Configurations which are instructed in document, but the result is same error:
  
 https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega/charts/hazelcast

 
Error:
  Failed to pull image "wfcertifiedvirtual.wfcr.wellsfargo.net/prmilm-aksilmpoc:1.3.2-11": rpc error: code = Unknown desc = failed to pull and unpack image "wfcertifiedvirtual.wfcr.wellsfargo.net/prmilm-aksilmpoc:1.3.2-11": failed to resolve reference "wfcertifiedvirtual.wfcr.wellsfargo.net/prmilm-aksilmpoc:1.3.2-11": failed to authorize: failed to fetch anonymous token: unexpected status: 401

This same repo connectivity successfully in pulling the Image with the below configuration with Tag as below: 
Please see the attachments and fix the authentication issue

![hazelcast configurations](https://user-images.githubusercontent.com/131379108/233401410-87cee6e9-1e9a-435c-a387-985a3e57b939.png)
![hazelcast configurations1](https://user-images.githubusercontent.com/131379108/233401735-689d8b35-e750-49e6-9274-f9d6a0d8c91f.png)

**Comment by MadhuriArugula** [comment]
@wreddybeem Error shared doesn't seem to be specific to the screenshots shared. `"wfcertifiedvirtual.wfcr.wellsfargo.net/prmilm-aksilmpoc:1.3.2-11": failed to authorize: failed to fetch anonymous token: unexpected status: 401` clearly is an issue with registry authentication. Please check if you have provided right details.

Also as mentioned in the documentation part of values.yaml, if platform version is greater than or equal to 8.8, use `clusteringServiceImage`, else `image` in the sub chart configuration

**Comment by kishorv10** [comment]
@wreddybeem Is the issue resolved? Can you update the latest status?

**Comment by misterdorito** [comment]
Given the lack of response, assuming the bug author is all set.  Closing this issue.
