### ISSUE TITLE
Jaas Config structure is unclear.

### ISSUE THREAD

**Issue by nemesis125** [pegasystems/pega-helm-charts#573]
I'm preparing an installation for an future use of Pega in Kubernetes (AKS). Now due to the recommendation of Pega (Loss of  support if used embededd) i started to split the the services. Till now everything worked fine. Even Kafka without any authentication worked fine. Now i want to set up an encrypted solution via SASL_SSL. So from Kafkas-view which i set up is everything ready and tested. Connection works fine etc. Now i wanted to implement it into the Helm-Chart. And there i'm facing an issue. I can't really tell how to implement it properly. Don't get me wrong. SecurityProtocol, saslMechanism and bootstrapServer is clearly understandable. But the definition of the value of jaasConfig is for me impossible to guess, how it should look like. I really would appreciate an example of an whole Stream definition for an SASL_SSL. Especially for the jaasConfig part. Thank you

**Comment by kishorv10** [comment]
@girirajguptagithub Can you please help with the query?

**Comment by gueney-suembuel** [comment]
> @girirajguptagithub Can you please help with the query?

Hi @kishorv10 

I found a solution to that which hopefully will help you. It is at least a orientation point how i could look like. Right now im working on a encrypted connection over sasl_ssl but if you want to connect without encryption of course you can let truststore,keystore empty.
![image](https://github.com/pegasystems/pega-helm-charts/assets/122539674/68c7555d-611f-41e5-9b98-f26b20d146b5)

**Comment by gueney-suembuel** [comment]
Hallo @kishorv10 actually i'am nemesis125, so i figured it somehow out ;)
