### ISSUE TITLE
Difference between in-place and out-of-place Upgrade Type

### ISSUE THREAD

**Issue by sunnygoel8** [pegasystems/pega-helm-charts#58]
Hi, 

Can anyone let me know the difference between in-place and out-of-place Upgrade type ?

**Comment by dcasavant** [comment]
Hi @sunnygoel8 ,

An in-place upgrade this will upgrade both rules and data in a single run. If your goal is to get to the upgraded version as quickly as possible regardless of downtime, then this might be the preferred option.

For an out-of-place upgrade, you would place your system into a state of code freeze, then migrate the rules to a new schema. Then upgrade the rules to the new version. Then separately upgrade the data. Although this is more involved, the advantage is you can upgrade the rules with users still running on the original system. So the downtime would only be when you were performing the data upgrade, and re-tuning your system to use the new rules schema (or migrating it back).  If your goal is to minimize downtime, this would be preferable.
