### ISSUE TITLE
Missing nodeSelector for search and hazelcast/clustering service pods

### ISSUE THREAD

**Issue by puravpat** [pegasystems/pega-helm-charts#580]
**Is your feature request related to a problem? Please describe.**
Have kubernetes cluster containing both Linux and Windows worker nodes so would like to have the ability to add node selector for the Search and Hazelcast/Clustering Service pods. This feature is already present for all the other pods created from the Web, Batch, or Stream tiers.

**Describe the solution you'd like**
Ability to add node selector for the search and Hazelcast/Clustering pods to launch the pod on specific node.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kishorv10** [comment]
US-612710 (internal)
