### ISSUE TITLE
Init containers fail to schedule because no resources requests/limits are defined

### ISSUE THREAD

**Issue by mina-alber** [pegasystems/pega-helm-charts#583]
**Describe the bug**

Pega charts only allow configuring resources requests/limits for the application containers, but the init containers fail to schedule because no resources requests/limits are defined.

**To Reproduce**

Install Pega in a namespace with a defined quota.

![Screenshot 2023-06-19 at 15 51 59](https://github.com/pegasystems/pega-helm-charts/assets/7760329/1441b808-42db-4177-9874-26c4ad22fe29)

> Error creating: pods "pega-batch-6dbc79b69c-8hxbz" is forbidden: failed quota: namespace-quota: must specify limits.cpu for: wait-for-pegasearch; limits.memory for: wait-for-pegasearch

**Expected behavior**

Add resources requests/limits to the init containers.

**Chart version**

All versions

**Comment by kishorv10** [comment]
#585  Is merged and available on the latest chart. Hence closing the issue.
