### ISSUE TITLE
Disabling Clustering Service

### ISSUE THREAD

**Issue by tiagothompson** [pegasystems/pega-helm-charts#591]
Dear support,

We are currently deploying Pega 8.8.2 thought Pega Helm Chart in OpenShift.

Our goal is for a small development environment. We are almost there but we are facing an issue regarding the helm chart.

We are unable to remove the clustering service in deployment time. We are not using the pega-hazelcast container, but the embedded hazelcast within pega-web-tomcat container.

When we set the variable clusteringServiceEnabled:false some resources that are required like variables are not implemented. So we need to leave it to true, but the clusteringService pod is just consuming resources without being used. We currently removing it after deploy, but we would like to have a clean deployment process and not be forced to deploy an unnecessary component.

Could you please help us with that?

 
Best Regards,

 Tiago Thompson

**Comment by kishorv10** [comment]
@vnihal72  Can you please suggest?

**Comment by vnihal72** [comment]
@tiagothompson, please make below two flag as false if you want embedded hazelcast.

hazelcast.enabled: false
hazelcast.clusteringServiceEnabled: false

**Comment by tiagothompson** [comment]
Thanks guys for the quick reply, we already tried that. 

When we set the clusteringServiceEnabled to false the clustering service is not deployed but it makes the pod pega-web crash because some variables related to hazelcast that are required during startup are not declared.

**Comment by kishorv10** [comment]
@tiagothompson Is the issue resolved? Can you update the latest status?
