### ISSUE TITLE
Zero Downtime Upgrade - Post-upgrade Job goes in Error

### ISSUE THREAD

**Issue by alemax22** [pegasystems/pega-helm-charts#596]
**Describe the bug**
We are upgrading our environments to the 8.7.5 version of Pega and the near-zero-downtime. procedure does not complete entirely, in fact the post-upgrade job goes in error. We had this issue in the TEST and PREP environments.

**To Reproduce**
Upgrade Pega Platform with near-zero-downtime procedure.

**Expected behavior**
Upgrade completes successfully without any issues.

**Chart version**
3.1.0 without customizations.

**Server (if applicable, please complete the following information):**
 - K8S
 - PostgreSQL

**Additional context**
I think that the issue is caused by the waiting time for the rollout of all the pods, which is too low for large environments like the one that we have: 2 batch pods, 6 web pods, 2 search pods. Kafka was externalized. The same issue was not present in the LAB environment, where the cluster dimensions are smaller.

**Comment by arvasrikanth** [comment]
@alemax22 Could you provide the logs for both the init containers and the actual post-upgrade container (if it is started) for further debugging purposes?

**Comment by pega-roska** [comment]
Closing issue due to lack of response.  Please re-open if you are still experiencing the issue.
