### ISSUE TITLE
Need only Linux nodes to be selected when Pods come up

### ISSUE THREAD

**Issue by vvinothkumar1** [pegasystems/pega-helm-charts#598]
**Is your feature request related to a problem? Please describe.**
yes while my cluster has both windows and linux,   Pods choose sometime windows machine, instead of linux,  so is there a way to restrict pods come up only in Linux node. 

**Describe the solution you'd like**
Pods to come up only in Linux. 

**Describe alternatives you've considered**
By giving in yaml file to restrict only to linux it is not working for node selector. 

**Additional context**
We are not able to restrict node selector to have only Windows or Linux in cluster level or namespace level in AKS. Pega.

**Comment by arvasrikanth** [comment]
@vvinothkumar1 This is not something pega can provide has a feature and there are various ways you can achieve this. Please check this [documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) from kubernetes site.
