### ISSUE TITLE
README.md - ESO documentation

### ISSUE THREAD

**Issue by charoensri** [pegasystems/pega-helm-charts#603]
**Describe the bug**
Documentation clarification on the use of ESO.
This statement in the https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md
"Update your values.yaml file to refer to the **external secret manager** for DB password."

**To Reproduce**
N/A

**Expected behavior**
perhaps the Charts and README.md should refer to the name of the Secret created by the ExternalSecret

**Chart version**
v3.2.0

**Server (if applicable, please complete the following information):**
NA

**Additional context**
NA

**Comment by APegaDavis** [comment]
@charoensri I've asked our doc team to take a look.

**Comment by kishorv10** [comment]
Required document changes are complete. Hence closing the issue.
