### ISSUE TITLE
Make DB2 udb in-file configuration properties configurable when using the chart as a dependency

### ISSUE THREAD

**Issue by micgoe** [pegasystems/pega-helm-charts#612]
**Is your feature request related to a problem? Please describe.**

When you try to install Pega on a `DB2` database using the setting `"global.actions.execute: install,"` you might encounter a failure in the job despite having correctly configured the JDBC connection properties. The database connection is established successfully, and the necessary tables are created. However, the job fails due to a database error. This problem arises because I haven't configured the connection properties in the `/charts/pega/charts/installer/config/udb` file. The default values provided in this file always lead to errors during installation. It's puzzling why incomplete defaults that inevitably lead to errors are defined.

The main issue, however, is centered around relying on a configuration file that cannot be edited when using the Pega Helm chart as a Helm repository or dependency. Unlike forking the chart, we're depending on the helm-repository directly. This reliance means we're unable to manipulate the file because it's an integral part of the dependency. This limitation becomes a significant challenge.

**Describe the solution you'd like**

Option A:
Enabling the option to specify the file path in the values.yaml allows me to provide my own file containing the necessary connection properties. However, I question the need for using external files for connection properties, especially considering that the property file is unlikely to be excessively large.

Option B:

Remove the existing default settings from the file. Connection properties can still be provided through the `jdbc.connectionProperties` variable.

Option C:

As a general approach, consider incorporating a file path variable for all external configuration files included within the chart, excluding template files. This should be implemented not only for the install sub-chart but also for the Pega chart's XML configuration files. This would enhance flexibility customization and readability when dealing with external configuration files.

**Describe alternatives you've considered**
- Post processing using kustomize and by that wiping out the default provided in the config file which are then merged in the resulting resources config map

**Additional context**
Overwriting the values by supplying the variable jdbc.connectionString won’t work. The file and the variable are being merged together.

**Comment by micgoe** [comment]
The request for this feature originates from a support ticket with Pega (INC-A10628). According to the information I received, my feedback has led to the creation of an internal enhancement request, labeled as FDBK-104038.

**Comment by APegaDavis** [comment]
Hi @micgoe, I agree having those values in the default file don't make much sense in general, and especially not for your usecase. I think the quick win will be to remove those values from the udb.conf file as those would never be valid out-of-the-box. I'll discuss with the team internally, but we should have this addressed shortly.

**Comment by micgoe** [comment]
Sounds great, thank you
