### ISSUE TITLE
Missing pegasystems/search image

### ISSUE THREAD

**Issue by wonim2022** [pegasystems/pega-helm-charts#617]
**Describe the bug**
I was trying to provision an environment using pega-helm-charts and found that pegasystems repository no longer contains pegasystems/search image that is required for the startup of pega-minikube container.

**To Reproduce**
Clone the repository, Set all the needed parameters in values-minimal.yaml file and launch using that set of values.

**Expected behavior**
All the images pull correctly and the cluster starts up.

**Chart version**
1.2.0 no customizations other that setting values-minimal to point to the postgres database and use embedded hazelcast.

**Server (if applicable, please complete the following information):**
 - OS: Windows 11
 - Environment: Minikube
 - Database: PostgresSQL

**Comment by shubi-github** [comment]
We are experiencing the same problem. Are there any updates or workarounds for it?
