### ISSUE TITLE
Article Mistake?

### ISSUE THREAD

**Issue by wakariyasuku** [pegasystems/pega-helm-charts#623]
**Question about RDS Size on Article of "Deploying Pega Platform on an Amazon EKS cluster"**
The article says "Select db.m5.large or greater. The db.m5.large selection provides the minimum hardware requirement for Pega Platform installations (a minimum of 4 vCores and 32 GB storage)"

But I guess db.m5.large has only 2 vCPUs, 8 GiB of memory.
So, what is the minimum spec that we use on deploying on AWS?

**Comment by kishorv10** [comment]
US-612703 (internal)

**Comment by kingakowalska1** [comment]
Fixed in https://github.com/pegasystems/pega-helm-charts/pull/803
