### ISSUE TITLE
Ability for extended securityContext configuration apart from runAsUser in pegasearch

### ISSUE THREAD

**Issue by micgoe** [pegasystems/pega-helm-charts#635]
**Is your feature request related to a problem? Please describe.**

Currently, we have the capability to configure the **`pegasearch.podSecurityContext.runAsUser`** parameter exclusively. Unfortunately, this configuration does not extend to other Kubernetes securityContext parameters.

In our OpenShift Container Platform (OCP) environment, there's a need to include supplementalGroups in the pod security-context.

**Describe the solution you'd like**
We need to enhance the flexibility of the **`pegasearch.podSecurityContext`** variable to accept any YAML input, thereby accommodating a wider range of securityContext configurations. This expansion will enable us to configure various Kubernetes securityContext parameters as needed.

**Describe alternatives you've considered**
We use kustomize post processing right now to embeed our securityContext configuration. However, this is not a a clean solution and this feature could be of benefit for various customers.

**Comment by kishorv10** [comment]
#660

**Comment by kishorv10** [comment]
US-570518 (internal)
