### ISSUE TITLE
Add securityContext.supplementalGroups to deployment

### ISSUE THREAD

**Issue by pegatim** [pegasystems/pega-helm-charts#659]
**Is your feature request related to a problem? Please describe.**

Client's OpenShift environment requires multiple NFS mounts in deployment, where it needs to support multiple gids from these volumes. Altering these gids isn't an option for these exports. So, per OpenShift's recommendation securityContext.supplementalGroups was implemented in the client's environment to support their use case. 

Reference:
https://docs.openshift.com/container-platform/4.13/storage/persistent_storage/persistent-storage-nfs.html#storage-persistent-storage-nfs-group-ids_persistent-storage-nfs

**Describe the solution you'd like**

Be able to implement securityContext.supplementalGroups feature via values file.

**Describe alternatives you've considered**
Request admin to modify NFS export, which was not an option. 

**Additional context**
From research, securityContext.supplementalGroups is supported from v1.23-v.1.28. 

Reference:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/

Feel free to hit me up if clarification is necessary.

**Comment by micgoe** [comment]
A feature we also need for the plugin search node. 
https://github.com/pegasystems/pega-helm-charts/issues/635

**Comment by pegatim** [comment]
@micgoe, regarding search node enhancement, with [Search and Reporting Service ](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/backingservices/charts/srs/README.md) available it may be a good idea to separate the enhancement request. Ref. #635, Kustomize is a good way to go for sure though.

**Comment by kishorv10** [comment]
#660

**Comment by kishorv10** [comment]
US-570518 (internal)
