### ISSUE TITLE
AKS cluster scaling fails due to pega-web-node volume node affinity conflict

### ISSUE THREAD

**Issue by FredrikLiindgren** [pegasystems/pega-helm-charts#663]
## Describe the bug
Sometimes when re-deploying the helm-chart after an uninstall 1 or more of the pega-web nodes gets stuck in "Pending" state
![pega-node-pending](https://github.com/pegasystems/pega-helm-charts/assets/56636445/bcfc1b45-2ae8-40be-97c9-b59aba6f26fe)

## To Reproduce
1. Install pega with the helm chart
2. run `helm uninstall <release-name> -n <namespace>` 
3. Re-deploy pega

## Expected behavior
Helm chart can be uninstalled and re-deployed without `volume node affinity conflict`

## Chart version
4.10.0  

## Server (if applicable, please complete the following information):
 - Environment: AKS
 - Database: PostgreSQL

## Additional context
Sometimes when re-deploying the helm-chart after an uninstall 1 or more of the pega-web nodes gets stuck in "Pending" state
![pega-node-pending](https://github.com/pegasystems/pega-helm-charts/assets/56636445/bcfc1b45-2ae8-40be-97c9-b59aba6f26fe)

Checking the events with `kubectl events` gets me the followin:
```
Normal    NotTriggerScaleUp        pod/pega-web-1                  pod didn't trigger scale-up: 1 Insufficient memory, 1 node(s) had volume node affinity conflict

Warning   FailedScheduling       pod/pega-web-1                0/8 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/network-unavailable: }, 2 node(s) had volume node affinity conflict, 5 Insufficient memory. preemption: 0/8 nodes are available: 3 Preemption is not helpful for scheduling, 5 No preemption victims found for incoming pod
```

Uninstalling the helm chart again, deleting the pvc associated with the pending node & re-deploying the chart solves this issue.

**Comment by maracle6** [comment]
Volume node affinity conflict means that your persistent volume is not available to all nodes in your kubernetes cluster.  For example, on a public cloud storage volumes may only be available to nodes in the availability zone the volume was created in.    In a scenario like that, you would need to ensure that every zone has enough capacity for the pods that require the volume.  I see in the message that 5 of your nodes were at capacity for memory -- one of those nodes likely could have attached the necessary volume.  Working with your administrator to scale up your cluster in the required zone should resolve this problem.

**Comment by kishorv10** [comment]
Hi, @FredrikLiindgren Are you able to overcome the issue?

As @maracle6 rightly said, for the stateful deployments same volumes need to be assigned to the workload during the upgrades or restarts, in the cloud deployments, make sure that sufficient worked nodes are available in the availability zone in which the pods are originally provisioned so that same volumes are re-attached.
