### ISSUE TITLE
Issue while upgrading pega from 8.8.2 to 8.8.3 

### ISSUE THREAD

**Issue by kneil31** [pegasystems/pega-helm-charts#682]
**Describe the bug**
We are currently upgrading the existing pega environment on GKE from 8.8.2 to 8.8.3 but facing issues while performing the upgrade with no response from the installer. 

**To Reproduce**
Update the installer image to 8.8.3
make the changes in the yaml to upgrade 
Run the Installer 

**Expected behavior**
Upgrade should be done and able to access the environment

**Chart version**
We are using piper/ACM

**Server (if applicable, please complete the following information):**
 - OS: 
 - Environment: GKE
 - Database: PostgreSQL

![Screenshot 2023-12-12 5 48 16 PM](https://github.com/pegasystems/pega-helm-charts/assets/153756884/d805f8d8-2f74-429b-9241-2e2163acf189)
![Screenshot 2023-12-12 5 47 55 PM](https://github.com/pegasystems/pega-helm-charts/assets/153756884/79451fff-18c7-48b6-b739-d67d3f3734a9)

[downloaded-logs-20231212-135720.csv](https://github.com/pegasystems/pega-helm-charts/files/13663291/downloaded-logs-20231212-135720.csv)

**Comment by MadhuriArugula** [comment]
@kneil31 Looks like an issue with the parameters passed for upgrade section. 
`Invalid action upgrade-deploy or upgrade_type passed`. Can you share the upgrade snippet section from values.yaml if you are still facing the issue.
