### ISSUE TITLE
Configure our custom labels in the helm charts for our Pega installed in Openshift.

### ISSUE THREAD

**Issue by momchilgochev** [pegasystems/pega-helm-charts#685]
**Is your feature request related to a problem? Please describe.**
We need to configure our custom labels in the helm charts for our Pega installed in Openshift. 

**Describe the solution you'd like**
We need to configure our custom labels in the helm charts for our Pega installed in Openshift. Please change the helm charts and add label parameters in them.
**Describe alternatives you've considered**

**Additional context**
We already created a ticket to Pega support and they proposed to open a new issue to github.

**Comment by MadhuriArugula** [comment]
@momchilgochev We have the requested feature enabled from v3.16.2 pega-helm-charts. 
You might want to configure `podLabels` under each tier to add appropriate labels.

**Comment by kishorv10** [comment]
`podLabels` feature is added as part of #709. Labels can be configured at the tier level. [Here](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values.yaml#L261) is the `values.yaml` configuration.
 
 As the required support is added. We are proceeding with closing the issue. Revert back in case of any issues.
