### ISSUE TITLE
We can’t find an option to set a secret for registry access regarding SRS charts 

### ISSUE THREAD

**Issue by momchilgochev** [pegasystems/pega-helm-charts#686]
**Is your feature request related to a problem? Please describe.**

We can’t find an option to set a secret for registry access regarding SRS charts 

**Describe the solution you'd like**

Please add an option for setting the username and password in secret.

**Describe alternatives you've considered**

**Additional context**
See the picture 
![image](https://github.com/pegasystems/pega-helm-charts/assets/154223570/a954b1b6-1d80-41fa-84a0-65f8e8a82af9)

**Comment by maracle6** [comment]
@momchilgochev Please check if release 3.13.0 resolves your issue (srsruntime.imagePullSecretNames)

**Comment by kishorv10** [comment]
#654 Addresses the issue. Hence closing it.
