### ISSUE TITLE
Startup probe failed: Get "http://podip:8080/prweb/PRRestService/monitor/pingService/ping": dial tcp podip:8080: connect: connection refused

### ISSUE THREAD

**Issue by tech-savvy-subh** [pegasystems/pega-helm-charts#691]
**Describe the bug**
While installing pega using this command ,  
helm install pega pega/pega --namespace mypega --values pega-web.yaml,
our pega web and batch pod is going on crashloopbackoff state ,
clusteringservice-0           1/1     Running            0                  12d
clusteringservice-1           1/1     Running            0                  12d
pega-batch-85f7958d94-9zpk4   0/1     CrashLoopBackOff   2264 (3m40s ago)   8d
pega-web-544f96cdb-b24k2      0/1     CrashLoopBackOff   2201 (48s ago)     8d

we have externalized our elasticsearch and kafka service .
 
web pod events,
Warning  Unhealthy  33m (x2400 over 8d)     kubelet  Startup probe failed: Get "http://podip:8080/prweb/PRRestService/monitor/pingService/ping": dial tcp podip:8080: connect: connection refused
  Warning  BackOff    3m21s (x51732 over 8d)  kubelet  Back-off restarting failed container pega-web-tomcat in pod pega-web-544f96cdb-b24k2_mypega(82cfc516-0431-41dc-af1b-1dbb898e3409)

surprisingly earlier pvs were getting created earlier but after externalizing both elasticsearch and kafka it is not happening

please help us fix this issue , let me know if i am not clear on the issue description and i can so that add more details.

**Expected behavior**

**Chart version**
pega-3.12.0

**Server (if applicable, please complete the following information):**
 - Environment: Amazon EKS,
 - Database: PostgreSQL

**Comment by pega-roska** [comment]
This kind of support request would probably be better handled via Pega Global Client Support.  They have more resources dedicated to doing in depth debugging.
