### ISSUE TITLE
Unable to load server.xml

### ISSUE THREAD

**Issue by gueney-suembuel** [pegasystems/pega-helm-charts#693]
**Describe the bug**
Due to the following change, he Pod for Web/Batch isn't able to start. > https://github.com/pegasystems/pega-helm-charts/commit/7d03c0fa8e26b2b5d32f62e2e0baca16e503b236

In the logs you can see following entry:
![image](https://github.com/pegasystems/pega-helm-charts/assets/122539674/7dde02a6-b828-47fb-976f-6197968b2a09)

**To Reproduce**
Update the helm repository and try to deploy.

**Expected behavior**
The pod will not start. In the logs an error is visible which tells you, that server.xml was unable to load.

**Chart version**
Pega 3.13.0

**Server (if applicable, please complete the following information):**
 - OS: Ubuntu (Node)
 - Environment: Azure AKS
 - Database: MSSQL

**Additional context**
-

**Comment by Saurabh-16** [comment]
Hi @gueney-suembuel , Can you please try to use the latest image. I believe you are using older docker images with latest helm charts. Can you please pull the latest image and let us know if the issue still persists?

**Comment by gueney-suembuel** [comment]
Hi @Saurabh-16 
I downloaded the latest docker image 8.8.2 and tried again with the same result.

**Comment by Saurabh-16** [comment]
Thanks @gueney-suembuel for the confirmation. I'm closing the issue now.
