### ISSUE TITLE
Incorrect scaling behavior of pega-web workload

### ISSUE THREAD

**Issue by johnbooth** [pegasystems/pega-helm-charts#702]
**Describe the bug**
When adjustments are made to either the global.tier[0].hpa.maxReplica or global.tier[0].hpa.minReplica settings within the Helm chart, the pega-web workload exhibits an unexpected behavior: it scales down to 1 replica and subsequently scales back up to the minReplica setting. This behavior poses a significant risk of service disruption and necessitates execution during a low-traffic maintenance window.

**To Reproduce**
Update the Helm chart with modifications to global.tier[0].hpa.maxReplicas.
Observe the pod rescheduling process for the pega-web workload.

**Expected behavior**
The expectation is to seamlessly increase the maxReplica setting without triggering unnecessary scaling events that disrupt service. This aligns with the standard behavior observed when modifying HPA settings via the GCP Console.

**Chart version**
3.6.0 - No customizations

**Server**
- Environment: GKE 1.27.7-gke.1121002
- Database: PostgreSQL

**Comment by MadhuriArugula** [comment]
@johnbooth We have reviewed the use case and do not see any issue with scaling behaviour when HPA is modified or even patched.
We do have enhancements provided in deployments HPA as part of latest chart releases https://github.com/pegasystems/pega-helm-charts/releases/tag/v3.16.1 where you can provide scaleUp/scaleDown strategies for HPA along with other supported parameters from Kubernetes. 

Can you please try the feature and let us know if you still see the issue. If you further require assistance on the same, I recommend you to raise a Pega Support Request.

**Comment by MadhuriArugula** [comment]
Closing the issue as per previous comment.
