### ISSUE TITLE
Error: INSTALLATION FAILED: template: pega/templates/_pega-k8s-ingress.tpl:35:3: executing "pega.k8s.ingress" at <include "defaultIngressRule" .>: error calling include: template: pega/templates/_helpers.tpl:144:15: executing "defaultIngressRule" at <include "hostPathType" $>: error calling include: template: pega/templates/_helpers.tpl:136:13: executing "hostPathType" at <.node.ingress.pathType>: nil pointer evaluating interface {}.pathType

### ISSUE THREAD

**Issue by RohitPoojary** [pegasystems/pega-helm-charts#722]
**Describe the bug**
Unable to perform helm install for pega .

**To Reproduce**
 helm install mypega pega/pega --namespace taqadhi-test --values pega.yaml --version 3.17.0 

**Expected behavior**
Deployment should be installed

**Chart version**
3.17.0

**Server (if applicable, please complete the following information):**
 - OS: NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
 - Environment:  Kubernetes "v1.26.3"
 - Database: mssql

**Comment by MadhuriArugula** [comment]
Hi @RohitPoojary 
I do not see an issue while running the command - ` helm install mypega pega/pega -n mypega --dry-run --version 3.17.0 --set global.provider=k8s` using default values.yaml file.
Are there any customisations to your values.yaml or templates?

**Comment by RohitPoojary** [comment]
> Hi @RohitPoojary I do not see an issue while running the command - ` helm install mypega pega/pega -n mypega --dry-run --version 3.17.0 --set global.provider=k8s` using default values.yaml file. Are there any customisations to your values.yaml or templates?

We see that for Stream tier type it is compulsory to expose it via ing? can it be kept optional?

**Comment by MadhuriArugula** [comment]
@RohitPoojary Ingress is never mandatory for any tier. You can skip the Ingress deployment for Stream by commenting/removing `ingress` section under stream tier.

**Comment by kishorv10** [comment]
Along with the above suggest, we recently delivered an explicit way to disable the ingress created ref #717 
Please try these options, let us know if you are still facing issues.
