### ISSUE TITLE
Running minikube version report error

### ISSUE THREAD

**Issue by damiandragowski** [pegasystems/pega-helm-charts#731]
During installation process on minikube we are getting:
"Error: found in Chart.yaml, but missing in charts/ directory: cassandra"

**To Reproduce**
run minikube and run command:

 helm install charts/pega/ -n mypega --generate-name --namespace pega --values charts/pega/values-minimal.yaml

**Expected behavior**
It shoudl install pega platfrom on minikube

**Chart version**
[What version of the charts are you using?  Have you made any customizations?](version: "3.17.0")

**Server (if applicable, please complete the following information):**
Fedora core 36

**Additional context**
lack

**Comment by kishorv10** [comment]
Hi @damiandragowski cassandra is a sub-chart of Pega. Its helm behavior to include/download subcharts before doing any helm action. Please run `helm dependency build` with in `~/pega-helm-charts/charts/pega` before performing actual installation.
