### ISSUE TITLE
Pega openshift deployment is failing to scan jar file

### ISSUE THREAD

**Issue by skfathima87** [pegasystems/pega-helm-charts#742]
**Describe the bug**
We were able to do the pega deployment with the custom image that included jdbc driver, but now we are trying to download the jdbc driver using custom artifactory but running into below issue.

06-May-2024 08:40:09.844 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.processURLs Failed to scan [file:/usr/local/tomcat/lib/ojdbc8-19.3.0.0.jar] from classloader hierarchy
Caused by: java.util.zip.ZipException: zip END header not found

06-May-2024 08:40:09.897 SEVERE [main] com.pega.pegarules.internal.bootstrap.PRBootstrapDataSource. Unable to connect to database.  Will only use properties from file.
	java.sql.SQLException: Cannot load JDBC driver class 'oracle.jdbc.OracleDriver'

**To Reproduce**
Pega 8.8.2 deployment with jdbc driver ojdbc8-19.3.0.0.jar

**Expected behavior**
Should be able to download jar and connect to database without any issues

**Chart version**
v3.17.0

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] 
 - Environment: [e.g. Amazon EKS, Open Source Kubernetes 1.11, etc.] Openshift
 - Database: [e.g. PostgreSQL] jdbc

**Additional context**

**Comment by pega-roska** [comment]
That error message suggest that the jar file being downloaded into the image is corrupt.  Are you sure the URL is correct and all necessary credentials are being provided?

**Comment by skfathima87** [comment]
Yeah, everything looks good. I am able to download the jar from that artifactory and verify.

**Comment by pega-roska** [comment]
Are you downloading the jar with exactly the same URL and credentials as are being passed into the chart?  Also are you sure communication from Openshift to Artifactory is not being intercepted?

The error message is not especially ambiguous.  The file being downloaded into the container is not a valid zip file.

**Comment by skfathima87** [comment]
I can see the jar file is being downloaded into the target directory, looks like the StandardJarScanner is failing to scan the file. I checked with our Openshift engineering folks too, they are mentioning that the issue is at the application level. PFA.

**Comment by pega-roska** [comment]
Are you sure that you are correctly configuring the customArtifactory section of values.yaml with the necessary credentials to connect to the artifactory server.  The container appears to be downloading something, but it doesn't seem like what it's getting is the jar.

**Comment by skfathima87** [comment]
Issue is with artifactory endpoint URL.  We are able to resolve the issue, you may close the ticket.
