### ISSUE TITLE
Cache dependencies for tests in travis

### ISSUE THREAD

**Issue by Max-Levitskiy** [pegasystems/pega-helm-charts#75]
**Is your feature request related to a problem? Please describe.**
_dep ensure_ takes much more time than _go test_ in build

**Describe the solution you'd like**
https://docs.travis-ci.com/user/caching/ - here is a description of how we can cache directories for builds.
It seems we need to cache terratest/pkg and terratest/src/test/vendor

**Comment by petejo** [comment]
We are now leveraging GitHub Actions instead of Travis CI
