### ISSUE TITLE
node-Affinity/node-selector for SRS chart

### ISSUE THREAD

**Issue by DandaRaviteja** [pegasystems/pega-helm-charts#783]
SRS chart is not having either node-affinity or node selector , can you please add to the helm chart.

**Comment by MadhuriArugula** [comment]
Node Affinity support is available in 3.24 release of pega-helm-charts.

**Comment by DandaRaviteja** [comment]
Looks like only podaffinity was added to srsservice_deployment.yaml, but not node affinity and tolerations, can you please confirm ?
