### ISSUE TITLE
Constellation Customer Asset Persistence is not Synchronized in New Pods

### ISSUE THREAD

**Issue by ansaries** [pegasystems/pega-helm-charts#801]
**Describe the bug**
I have created the Constellation App Static Service as a StatefullSet, allowing it to use the same PVC upon restart. However, every time a new Pod is created it does not copy the customer assets into its `components` folder as a new folder with the name of the webnode pod is created in the `customers` folder.

**To Reproduce**
Kill a running WebNode Pod, it will recreate the Pod with a new name.

**Expected behavior**
Constellation App Static should copy the customer assets into the newly created `<folder with webnode's newly created pod name>/components`

**Chart version**
Latest

**Server (if applicable, please complete the following information):**
 - OS: NA
 - Environment: GKE (Kubernetes)
 - Database: PostgreSQL

**Additional context**

<img width="751" alt="Screenshot 2024-08-18 at 4 23 15 PM" src="https://github.com/user-attachments/assets/47a033bf-cac1-4ba5-9060-4bafa09cbc1f">

<img width="1190" alt="Screenshot 2024-08-20 at 10 59 08 AM" src="https://github.com/user-attachments/assets/b4740ce8-723c-485f-9331-2688fe742056">

**Comment by mithra-keth** [comment]
Hi, @ansaries Could you please go to Infinity's dev studio Clipboard -> System Pages and select pxProcess and check the values for environmentID and pxSystemName before and after restart? Do they change on restart? Could you please share those details? Thanks!

**Comment by nikhilparmar86** [comment]
And also pxSystemNode.

**Comment by ansaries** [comment]
> pxSystemNode

Yes, offcourse.

**Comment by ansaries** [comment]
> Hi, @ansaries Could you please go to Infinity's dev studio Clipboard -> System Pages and select pxProcess and check the values for environmentID and pxSystemName before and after restart? Do they change on restart? Could you please share those details? Thanks!

Sure I will do it and will provide info as asked.

**Comment by ansaries** [comment]
> environmentID

Hey @nikhilparmar86 yes the hostnames get updated in the px process. following are the evidences:
**Before:** 
<img width="654" alt="Screenshot 2024-08-24 at 4 23 35 PM" src="https://github.com/user-attachments/assets/ca2b5621-dfaf-4fa3-8f11-cc517b217a18">
<img width="864" alt="Screenshot 2024-08-24 at 4 24 47 PM" src="https://github.com/user-attachments/assets/ec9cf488-41cf-4a8a-aaa1-f16bb2a323df">

**After:** 
<img width="957" alt="Screenshot 2024-08-24 at 4 51 37 PM" src="https://github.com/user-attachments/assets/75e56279-139e-4571-8d0b-eb2df982a887">
<img width="676" alt="Screenshot 2024-08-24 at 4 48 51 PM" src="https://github.com/user-attachments/assets/d8ff61db-40cb-4481-a54c-333a0d696949">
<img width="688" alt="Screenshot 2024-08-24 at 4 49 20 PM" src="https://github.com/user-attachments/assets/c022a622-319c-4c3a-9e3b-3af2faacdd28">


I hope this answers the question.

**Comment by nikhilparmar86** [comment]
Thank you @ansaries for your response. 
This is the reason for your issue. 
Is it possible for you, Can we try to set a fixed value for systemname or nodename at the time of deployment?

**Comment by ansaries** [comment]
> Thank you @ansaries for your response. This is the reason for your issue. Is it possible for you, Can we try to set a fixed value for systemname or nodename at the time of deployment?

Hey @nikhilparmar86, I will have to deploy the Pega Nodes as a Statefull-Set instead of Deployment.
Will it be ok to do that?

**Comment by ansaries** [comment]
Thank you for your support.
