### ISSUE TITLE
PSQLException during "install-deploy"

### ISSUE THREAD

**Issue by skfathima87** [pegasystems/pega-helm-charts#849]
**Describe the bug**
We are migrating Pega application from VM to openshift cloud but the pods are going down quite frequently. Pega support team is suspecting that the issue is with database copy from VM based deployment. 

SO I started doing fresh installation of 8.8.3 using "install-deploy" and running into issues. **pega-db-install pod is not mounting certs into container & failing to find the certs.** 
**Caused by: org.postgresql.util.PSQLException: Could not open SSL root certificate file /opt/pega/pgsqlcerts/pgSQL.ca.cert.
Caused by: java.io.FileNotFoundException: /opt/pega/pgsqlcerts/pgSQL.ca.cert (No such file or directory)**

We did not face this issue while deploying & connecting to the DB copy using "deploy" option.  

**To Reproduce**
Deploy 8.8.3 & connect to postgres database. Connection requires necessary postgres certs.

**Expected behavior**
Install & deploy should go fine.

**Chart version**
(version: "3.24.3") 

**Server (if applicable, please complete the following information):**
 - Environment: Openshift
 - Database: PostgreSQL

**Comment by skfathima87** [comment]
Team, any update on this request.

**Comment by skfathima87** [comment]
Thanks @pega-roska, Issue with custom volume mounts is resolved. 

Pods are up & running fine for few mins but then throwing 504 gateway timeout error. Issue exist in both deployments with existing DB copy & the new deployment. Are you aware of this behavior. 

In addition, we are using Pega 8.8.3 installer and Pega images for deployment but log indicates the Pega engine code 08-08-04. May I know if it is an expected behavior? If not what can cause this issue.  Please advise.

18-Nov-2024 21:49:59.569 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap.
============ PegaRULES Bootstrap Configuration ============
Date: Mon Nov 18 21:49:59 GMT 2024
Java Version: Eclipse Adoptium 11.0.24
Configuration: file:/usr/local/tomcat/webapps/prweb/WEB-INF/classes/prbootstrap.properties
**Pega-EngineCode: 08-08-04**
ASM Version: 1764110373
Database: PostgreSQL 13.11
Driver: PostgreSQL JDBC Driver 42.3.3
Active CodeSets: **pega-enginecode:08-08-04** at (latest patch)
customer:06-01-01 at (latest patch)
=============== End Bootstrap Configuration ===============

**Comment by skfathima87** [comment]
504 Gateway Time-out
The server didn't respond in time.
![image](https://github.com/user-attachments/assets/bc7f203e-6950-44c9-a7cc-216e1cdd0487)

**Comment by skfathima87** [comment]
[Uploading pega-web-cfd69c44d-m6ljw-pega-web-tomcat.log…]()

**Comment by pega-talba** [comment]
Hi @skfathima87 - for the issues you're seeing here, it would be best for you to have a dedicated person from our support teams to work with you directly. If you [create a support ticket](https://support.pega.com/support-doc/creating-support-ticket) on [My Support Portal](https://msp.pega.com/) then you should get an active support engineer to help work with you on this issue. You can reference this Issue in the support ticket so they can quickly catch up on what's been discussed so far.

**Comment by skfathima87** [comment]
Sure, thank you!
