### ISSUE TITLE
Check-in charts manifest file also in Git repo.

### ISSUE THREAD

**Issue by sunnygoel8** [pegasystems/pega-helm-charts#86]
we pulled down pega repo from following location and installed pega chart on PKS. After deploying the chart, we can see the chart version **1.2.4**

https://dl.bintray.com/pegasystems/pega-helm-charts

But chart manifest in Github repo. still shows **1.2.0** .. It will be better to check-in chart manifest files also in GitHub to provide a consistent bahavior.

**Comment by dcasavant** [comment]
Hi @sunnygoel8 - great feedback.  I'll pass it along to the team and will see about getting it scheduled.

**Comment by sunnygoel8** [comment]
Thanks @dcasavant
