### ISSUE TITLE
custom prconfig.xml settings are not picked up

### ISSUE THREAD

**Issue by PegaBasis** [pegasystems/pega-helm-charts#91]
**Describe the bug**
We edited the pega-helm-charts/charts/pega/config/deploy/prconfig.xml file to include a different SystemName and Production level. However when we turn on the system it still has the old values (from the initial install)

        <env name="Identification/SystemName" value="newsystemname" />
        <env name="Identification/ProductionLevel" value="1" />

**To Reproduce**
- Install pega 8.3.1 on a new database with system name and production level (in my case system name = 'pega' production level = '2'.
- Edit the prconfig.xml file.
- Roll out the new configuration.

**Expected behavior**
Pega environment starts with the new system name and production level, as specified in the prconfig.xml

**Chart version**
6 commits behind master.

**Server (if applicable, please complete the following information):**
 - OS: Redhat linux
 - Environment: Openshift 4.2
 - Database: PostgreSQL 11

**Comment by dcasavant** [comment]
@PegaBasis A few questions to better help isolate the problem...

1. Is the prconfig change making its way into the container?  There are few places where it could be hung up, but the best way to check is to view the file in the running Pod to see what you get.

2. Is there a Data-Admin-System-Setting that may be overriding your config?  

If these checks both come back as ok, I would suggest engaging with GCS so a joint debugging session can be scheduled.

**Comment by Emilio-Pega** [comment]
Maybe another incedent of

**Comment by PegaBasis** [comment]
@dcasavant 
1. yes we are seeing the setting in the pega-web/pega-batch config map. However when looking at the deployment -> environment I only see the pega-environment-config, is this correct behaviour?
![environment-config](https://user-images.githubusercontent.com/58681895/75134196-d9334b00-56dd-11ea-9ca6-0bf6c8ed984c.PNG)

2. This dynamic system setting is present: prconfig/identification/systemName/default

**Comment by PegaBasis** [comment]
Hi @dcasavant I found the issue. It was related to https://github.com/pegasystems/docker-pega-web-ready/issues/50

My problem is now solved, so you can close the bug
